### ISSUE TITLE
Contributing guide should state forking the repo

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#1007]
In [this section](https://github.com/ploomber/ploomber/blob/master/CONTRIBUTING.md#setup-with-conda), we state cloning the repo, prior to that the user should fork the repo into their accounts and only then fork that repo.

**Comment by AnInventor** [comment]
Hi, I have added instruction as well as image for reference and raised pr for same https://github.com/ploomber/ploomber/pull/1018.
