### ISSUE TITLE
ploomber cloud documentation improvments

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#1046]
I reviewed the docs and found a few things we can improve in the notebook API documentation.

[This section](https://docs.ploomber.io/en/latest/cloud/cloud-notebook-parametrized.html) is named "running experiments in parallel"  but its more than that. It's showing how to configure notebooks with input data, request resources, etc. I think we should name it something like "Cloud notebooks user guide"

also, we should ensure that we're linking from [here](https://docs.ploomber.io/en/latest/cloud/cloud-notebook-simple.html) to the other tutorial since users that are getting started might be interested in learning more advanced features.

also, to configure the notebooks, we require users to add a raw cell, but many people don't know how to do it. we should add a GIF that shows how do it.

the older tutorials also need some renaming. this one should be "cloud pipelines": https://docs.ploomber.io/en/latest/cloud/cloud-execution.html
and this one: https://docs.ploomber.io/en/latest/cloud/guide.html "cloud pipelines user guide"

Then, we should connect the two: tell people reading "cloud notebooks user guide" that they can run multiple notebooks and direct them to the "cloud pipelines user guide". and from the "cloud pipelines user guide" that the "cloud notebooks user guide"  offers a simple API for projects that fit in a single notebook

**Comment by RodolfoFerro** [comment]
### Section names

- Notebooks API getting started
- Notebooks API user guide
- Pipelines API getting started
- Pipelines API user guide
