### ISSUE TITLE
Populate Slack Welcome message

### ISSUE THREAD

**Issue by jinniw43805** [ploomber/ploomber#1057]
Context:
Currently, we will send the user a welcome message when user joins the Ploomber Slack Workspace.
We may consider to provide the list of our current links.

Example - Ideal After:
<img width="768" alt="Screenshot 2023-01-02 at 9 26 32 PM" src="https://user-images.githubusercontent.com/9766828/210292932-b20a7a26-8591-4dd0-b1ce-95ff5fa4efd8.png">

Example - Currently Implementation:
<img width="901" alt="Screenshot 2023-01-02 at 9 30 49 PM" src="https://user-images.githubusercontent.com/9766828/210293134-f2b0e0d1-1948-4e2d-b494-fdca8440642a.png">

Action Item:

- [ ] Discuss if providing those links will help users to find the resource easier
  - What to include in the list? Currently we can have Ploomber.io, Github link, Doc link, Blog link
- [ ] Modify the bot message with the new adding section

**Comment by tonykploomber** [comment]
@idomic 
Do you think it's possible to grant the permission to edit the Slack Bot?
