### ISSUE TITLE
helping users when setting their key

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#1058]
I got a report from a cloud user that they had a "malformed API key error", somewhere in our docs, we have the following instructions:

```sh
ploomber cloud set-key {your-key}
```

And the user was setting it with the `{}` characters. We should detect if the passed key begins with `{` and ends with `}`. If so, ignore those characters (or maybe show an error telling them to remove them?)

**Comment by idomic** [comment]
I think we can simply solve it with a comment in the guide, something along the lines:
# i.e: `ploomber cloud set-key ABI8475@ODMFMOMD`

**Comment by tonykploomber** [comment]
I think we should apply both:
Providing the example in guide + `{}` characters error detection
