### ISSUE TITLE
Unable to Build docs during on dev environment

### ISSUE THREAD

**Issue by tonykploomber** [ploomber/ploomber#1064]
Issue:

I was following the [CONTRIBUTING GUIDE](https://github.com/ploomber/ploomber/blob/master/doc/CONTRIBUTING.md) to make the change on docs, however I was facing this issue after typed the `invoke docs` command

```
Notebook error:
OSError in cloud/cloud-notebooks-getting-started.ipynb:
[Errno 86] Bad CPU type in executable: 'pandoc'
make: *** [Makefile:23: html] Error 2
(ploomber) tonykuo@ ploomber % 
```

Complete Log:
https://pastebin.com/831YqqFe 

Not sure if anything related to CPU type, but I am using the Apple M2 Pro at this moment

Possible related issue
https://stackoverflow.com/questions/74979639/unable-to-knit-pdf-on-m2-mac-pandoc-error-applications-rstudio-app-contents-res

**Comment by idomic** [comment]
Check out [this thread](https://stackoverflow.com/questions/60859527/how-to-solve-pdftk-bad-cpu-type-in-executable-on-mac), I think you might need the roseta VM for that.

**Comment by idomic** [comment]
**Update:**
I'm able to build the docs fine (M1).
Make sure you follow the instructions in ploomber/doc/CONTRIBUTING.md

**Comment by tonykploomber** [comment]
Somehow I was able to resolve the issue by installing the pandoc manually
`brew install pandoc`

We can close the issue now, however, we should keep in mind if this issue happens in other people's environment

**Comment by edublancas** [comment]
either something in our docs is missing or the installation script is wrong because pandoc is part of the documentation requirements: https://github.com/ploomber/ploomber/blob/master/doc/environment.yml
