### ISSUE TITLE
Noqa coming up on docs

### ISSUE THREAD

**Issue by tonykploomber** [ploomber/ploomber#1070]
Followup of https://github.com/ploomber/sklearn-evaluation/issues/246

noqa visible [here](https://sklearn-evaluation.ploomber.io/en/latest/api/nbs.html)

<img width="872" alt="Screenshot 2023-01-30 at 4 33 08 PM" src="https://user-images.githubusercontent.com/123580782/215600070-4d1c11da-770f-4fb3-a20d-b64664d21250.png">

**Comment by tonykploomber** [comment]
https://docs.ploomber.io/en/latest/api/_modules/tasks/ploomber.tasks.NotebookRunner.html

<img width="273" alt="Screenshot 2023-01-30 at 4 35 16 PM" src="https://user-images.githubusercontent.com/123580782/215600309-42d6ea4e-82b1-48e7-a2c3-2139639e92bd.png">

**Comment by tonykploomber** [comment]
https://docs.ploomber.io/en/latest/api/_modules/tasks/ploomber.tasks.SQLDump.html

<img width="217" alt="Screenshot 2023-01-30 at 4 36 02 PM" src="https://user-images.githubusercontent.com/123580782/215600489-b156455a-4fd8-422b-a3f5-19f0c268011a.png">

**Comment by idomic** [comment]
Waiting for a PR.
Let's run it on ploomber-engine and jupysql as well.
