### ISSUE TITLE
ScriptRunner: Cannot import modules when other directories

### ISSUE THREAD

**Issue by nilbro** [ploomber/ploomber#1072]
I am trying to run the pipeline via the ScriptRunner and am not able to import modules from other directories. 
My current project structure looks like this:
```
└── project/
    ├── common/
    │   └── lib
    ├── file1.py --> want to import common.lib here
    ├── file2.py
    └── pipeline.yaml
```
Adding the project to the sys.path fixes this issues.

Note: This behaviour is not observed with the default NotebookRunner.

**Comment by edublancas** [comment]
thanks for your feedback, we'll get to it!

**Comment by eromoe** [comment]
I have same requetst . Now I have to use sys.path.insert in every script .

**Comment by edublancas** [comment]
@mehtamohit013 will work on this, so it will be fixed in the next version!

**Comment by nilbro** [comment]
Thanks
