### ISSUE TITLE
Parallel algorithms

### ISSUE THREAD

**Issue by robertdj** [ploomber/ploomber#1078]
Hi

I am making a pipeline to train an embarrassingly parallel model like a random forest. I can usually achieve a speedup by training the trees in parallel. However, scikit-learn's `n_jobs` seems to be ignored by Ploomber.

I have read Ploomber's docs about serial and parallel executors, but my understanding is that this relates to the nodes in Ploomber's DAG and not parallelization *within* each node.

Is it possible to do this kind of parallelization? 

Thanks!

**Comment by edublancas** [comment]
Hi!

> I am making a pipeline to train an embarrassingly parallel model like a random forest. I can usually achieve a speedup by training the trees in parallel. However, scikit-learn's n_jobs seems to be ignored by Ploomber.

what do you mean by ignored by Ploomber? You can use n_jons within a task, it should behave in the same way.

> I have read Ploomber's docs about serial and parallel executors, but my understanding is that this relates to the nodes in Ploomber's DAG and not parallelization within each node.

Correct.

> Is it possible to do this kind of parallelization?

What's the desired  behavior?

**Comment by robertdj** [comment]
Hello again.

Thanks for your swift response and apologies for my slow response. 

I don't know what I did to not make it work, but I made a new project and here it works as expected. Thanks!
