### ISSUE TITLE
Static analysis of ipynb task finds erroneous missing references when using "magics"

### ISSUE THREAD

**Issue by marr75** [ploomber/ploomber#1089]
Was trying out jupysql in a pipeline and discovered it would only work in an ipynb formatted task. Static analysis must be disabled to execute the task since any variables assigned in the magic are not understood by the static analysis processor.

I can provide a minimum example to recreate if necessary but as it involves ipynb, can't easily reconstruct it in markdown here.

**Comment by edublancas** [comment]
please share an example! (you can attach a zipped file with the notebook)
