### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by robertdj** [ploomber/ploomber#1102]
Hi!

I am running into memory issues when using Ploomber on large(-ish) datasets. Kinda hard to reproduce, so I'll start with a description. Let me know if more is needed.

When running a Ploomber pipeline the memory consumption of the Python process is increasing throughout -- as if does not release memory after finishing a step. 
Sometimes the Python process is killed with an "Out of Memory" exception during a step.
If I then re-run the pipeline (such that it starts with the step where it was just killed) it works w/o errors. 

Is this a behavior that others recognize? Can I do anything on my end to circumvent this?

Thanks!

**Comment by edublancas** [comment]
what kind of tasks are you using? (functions, notebooks), and are you changing any settings in the executor?

**Comment by robertdj** [comment]
I'm only using functions. I use these settings:

```yaml
executor:
  dotted_path: ploomber.executors.Serial
  build_in_subprocess: false 
```

Quite basic pipeline: Load data, wrangle it, fit a model & save it, make predictions with model.

There is also and `env.yaml` file with configurations.

**Comment by edublancas** [comment]
cool, in such case, you might wanna look at polars documentation, maybe there is something about memory management.
