### ISSUE TITLE
Papermill with python 3.11

### ISSUE THREAD

**Issue by afonit** [ploomber/ploomber#1103]
Not sure if this is the right place to report this - I saw your project uses papermill, and it looks like there are issues with papermill supporting python 3.11.  I don't know if there is an interest or technical knowledge in assisting getting that pushed through:

Issue:
https://github.com/nteract/papermill/issues/700

Pull request:
https://github.com/nteract/papermill/pull/708

**Comment by edublancas** [comment]
hi, thanks for your feedback!

papermill hasn't received much maintenance lately so we decided to build our own notebook executor ([ploomber-engine](https://github.com/ploomber/ploomber-engine)). so our dependency on papermill is considered legacy at this point and we'll remove it in the future.
