### ISSUE TITLE
clean up tests and better error message with R notebooks

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#1109]
we need to address a few things from this PR: https://github.com/ploomber/ploomber/pull/1101

1. refactor unit tests: https://github.com/ploomber/ploomber/pull/1101#discussion_r1212466632
2. better error message when trying to run an R notebook with ploomber-engine https://github.com/ploomber/ploomber/pull/1101#discussion_r1211999094

**Comment by edublancas** [comment]
any updates here?

**Comment by mehtamohit013** [comment]
It got sidetracked due to the DuckDB issue (because it was a `high priority`). 
Working on it now...
