### ISSUE TITLE
remove `ploomber cloud`

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#1114]
follow up of: #1111 

we also need to remove it from our docs (see `hooks.py`) and delete the notebooks from https://github.com/ploomber/projects

**Comment by lbellomo** [comment]
I can't find references to cloud, so it seems that it is already resolved:
- The hook [part](https://github.com/ploomber/ploomber/commit/ce21092982c26536776a282f927bbc41cf3624f9#diff-b556882f6e9933478e543d3f38f0600d32c6f10630899e704ce89ef31aecd978)
- The notebooks [part](https://github.com/ploomber/projects/commit/276bf25550449ebf5a48c4cd83854f2977de1a1d)
- And this [one](https://github.com/ploomber/ploomber/commit/8e5183083637847c629998b7888b5be994551491)

**Comment by edublancas** [comment]
thanks for looking at this! we probably fixed this but forgot to close the issue!
