### ISSUE TITLE
QUESTION on example at README

### ISSUE THREAD

**Issue by pybokeh** [ploomber/ploomber#14]
Hello!  Just checking out this new library.  There is one line that is confusing to me which I don't understand.  The comment of course says what it does, but the API syntax is very strange to me:

```
task_add_one.on_finish = on_finish
```

What is strange to me is that the on_finish function somehow gets attached to the task_add_one and you don't pass a parameter to it.  Does this line belong here?

**Comment by pybokeh** [comment]
I discovered this example [page](https://ploomber.readthedocs.io/en/latest/auto_examples/basic.html#sphx-glr-auto-examples-basic-py).

Looks like this example left out that line.

**Comment by edublancas** [comment]
Hi,

Thanks for pointing this out. Such syntax is not very common but perfectly valid: https://docs.python.org/3/tutorial/classes.html#instance-objects

But I agree that including an on_finish parameter to the task constructor would make this more consistent.
