### ISSUE TITLE
cli.parser refactoring

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#211]
A lot of parts in this module inspect function signatures, we should only do this once as this is not very efficient, instead of having separate functions call `inspec.signature` many times

**Comment by idomic** [comment]
@edublancas more context here?

**Comment by edublancas** [comment]
this is low priority but here are more details:

In the cli.parser module we're calling `inspec.signature` multiple times (and some other functions). It'd be better to cache this results to make it faster (e.g. implement a class that stores the results).

I'm unsure how much this will improve performance, so let's close this. since the CLI performance isn't bad
