### ISSUE TITLE
Consider showing an error when the parameters cell defines other variables than upstream and product

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#229]
It might indicate a missing cell separator, hence those lines will happen before the injected parameters and might break

The problem is that other variables might be present if the Task receives non-empty `param`, especially if static analysis is on.

**Comment by edublancas** [comment]
Maybe just show a warning

**Comment by idomic** [comment]
@jramirez857 want to tackle another one?

**Comment by edublancas** [comment]
sorry, this is no longer relevant - it's two years old, we made a few changes since then
