### ISSUE TITLE
Fix CI warnings

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#269]
`pytest` is throwing a lot of warnings in the CI logs, we should go one by one and fix them. I'm sure there are many factors behind this but fixing at least some of this helps. running the test suite locally should show the warnings as well.

we don't want to hide the warnings because the show important information, but rather see which ones we can fix

**Comment by idomic** [comment]
@edublancas please add issue description

**Comment by AugustasV** [comment]
Made pull request with filter that will ignore Deprecation Warnings.
