### ISSUE TITLE
Document how to send custom parameters to nbconvert

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#276]
We use the official nbconvert package to export notebooks to different formats. Each output format has some extra options that users can set via the `nbconvert_export_kwargs` parameter in `NotebookRunner` (such as hiding input cells). However, these details are hidden in the Python API docs, and even there, they aren't explained clearly:

- [x] Document in NotebookRunner some uses cases for custom args
- [x] Also document this in the user guide for people who uses the spec API (YAML)

Thanks @grst for reporting!

**Comment by grst** [comment]
in that respect, you might find this issue interesting (to stay compatible with Rmarkdown & jupytext): 
https://github.com/mwouts/jupytext/issues/337

**Comment by edublancas** [comment]
Added link showing how to pass nbconvert args to an example (which is hyperlinked from the docs): https://github.com/ploomber/projects/blob/master/ml-intermediate/pipeline.yaml

Also added code example using the Python API: https://github.com/ploomber/ploomber/blob/808679b0839768b02f7ee3ab84540a57f2fe2bc6/src/ploomber/tasks/notebook.py#L211
