### ISSUE TITLE
Display relative, rather than absolute, paths in DAG plot

### ISSUE THREAD

**Issue by aeturrell** [ploomber/ploomber#279]
- ploomber, version 0.8.4
- MacOS Catalina

When calling `ploomber plot`, the generated DAG displays absolute path names by default. Change the default behaviour to display pathnames relative to the directory in which ploomber was called.
Benefits of this:
-  For projects, ploomber will often be called from the root directory as monitored by git, so this is the natural folder to display paths in DAGs relative to
- Absolute paths give details of users' computer configuration
- Relative pathnames are less cluttered (with extraneous information)

**Comment by edublancas** [comment]
Hi, thanks for your feedback!

Improving the generated plot is long overdue. Not only what information is displayed but the graph itself. I'll add this to the to-do list for the next release.

Feel free to send any other comments.

**Comment by aeturrell** [comment]
Amazing! 🎉
