### ISSUE TITLE
Ploomber vs (and ?) MLFlow

### ISSUE THREAD

**Issue by 99snowleopards** [ploomber/ploomber#289]
thank you for releasing this library - it looks very helpful! thank you also for posting a detailed comparison (survey of WMS tools)

I'm still new to MLOps/WMS - could you help me compare Ploomber to MLFlow (https://github.com/mlflow/mlflow) - would Ploomber be a substitute for MLFlow, or complement it?

Thanks,

**Comment by edublancas** [comment]
Hi,

Great question! This is something that comes up a lot, I'm preparing a blog post :)

They are complementary tools. Workflow managers help you orchestrate your pipeline (from data ingestion to model training), tools such as MLFlow allow you to track your models. For example, you may write a pipeline that generates features and at the end trains different models (e.g., random forest, neural network, SVM, etc). Ploomber can help you write that orchestration pipeline and at the end, you can add some MLFlow code to track the metrics for each trained model.

Recently, MLFlow added orchestration capabilities, but they're very simple IMO, Ploomber is much more flexible in that end. I think Ploomber + MLFlow is overall a good combination.

If you decide to use Ploomber for your projects, do not hesitate to reach out if you have more questions!

**Comment by 99snowleopards** [comment]
thank you for the fast and detailed and fast response - very excited to learn more about Ploomber, looking forward to more blogs and updates :)
