### ISSUE TITLE
Make ploomber installable via conda

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#292]

**Comment by rdmolony** [comment]
Hey @edublancas - I put together a conda-forge submission to resolve this issue, when you get the chance would you mind reviewing the proposed recipe?  Also, is it okay to list you as a maintainer on it?

**Comment by edublancas** [comment]
Hi @rdmolony thanks for your contribution!

Looks like the recipe is broken: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=340729&view=logs&jobId=6f142865-96c3-535c-b7ea-873d86b887bd&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823

```
    check_recipes_in_correct_dir(root_dir, "recipes")
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 164, in check_recipes_in_correct_dir
    raise RuntimeError(f"recipe {path.parts} in wrong directory")
RuntimeError: recipe ('meta.yaml',) in wrong directory
##[error]Bash exited with code '1'.
```

Might be worth checking out a [previous attempt](https://github.com/conda-forge/staged-recipes/pull/14843). I think that one was pretty much done but there was an issue with the latest ploomber version at that time that should be fixed now. Let me know how can I help.

**Comment by rdmolony** [comment]
Thanks @edblancas - I'll take it up from there, hopefully it's easy enough!  I really like the ploomber package from the extensive docs & examples - hopefully this will make it more cross-compatible (Windows 👀)

**Comment by rdmolony** [comment]
I didn't have push permissions to @RoyalTS branch (naturally) so I just copied his edits across to my branch and resumed the PR

**Comment by rdmolony** [comment]
CI is now passing, I've pinged the `conda-forge-admin` user to flag PR (I'm a first time contributor so can't contact `conda-forge/help-python`

**Comment by edublancas** [comment]
Fantastic! Thanks again!

Whenever you find some extra time, It'd be great if you can update the docs and open a PR. This way you'll appear as a contributor in the home page :)

https://github.com/ploomber/ploomber/blob/master/doc/get-started/install.rst
