### ISSUE TITLE
DB API specification

### ISSUE THREAD

**Issue by alborotogarcia** [ploomber/ploomber#299]
Hi Ploomber team! 

I'd like to know if ploomber db api is it tightly coupled with sqlalchemy or it can be extended easily to support other PEP 248 as turbodbc? support for turbodbc would help with arrow pipeline ecosystem (also Arrow Flight)

And how will ploomber fit in argo dataflow roadmap?

**Comment by edublancas** [comment]
Hi, thanks for your message.

If your db isn't supported by sqlalchemy, you can use the generic [db client](https://ploomber.readthedocs.io/en/latest/api/_modules/clients/ploomber.clients.DBAPIClient.html#ploomber.clients.DBAPIClient). As long as the driver conforms to the DB API, it should work.

I don't know much about argo dataflow (I chatted a bit with one of Argo's maintainers about it a few months ago). For the time being, Ploomber is conceived more like a batch processing solution but as argo dataflow matures, we'll definitely consider an integration.

I'm curious to learn more about your use case to give a more informed recommendation. Feel free to share more details here or drop me a line eduardo@ploomber.io
