### ISSUE TITLE
Switching env.yaml from the command line

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#309]
Currently, the only way to load a different `env.yaml` is via an environment variable

```sh
export PLOOMBER_ENV_FILENAME=env.production.yaml && ploomber build
```

But it'd be useful to also expose this as a parameter

```sh
ploomber build --env env.production.yaml
```

**Comment by idomic** [comment]
Hey @tharun634 any updates?

**Comment by edublancas** [comment]
closing this in favor of #400
