### ISSUE TITLE
DAGMapping should ignore non-notebook tasks

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#315]
DAGMapping currently creates a map of all tasks but it should only do so for notebook/script tasks. e.g., ignore tasks whose source is a function or a SQL script:

Essentially we want to move the `pairs` iteration logic inside the `DAGMapping` constructor:

https://github.com/ploomber/ploomber/blob/c87c60db954f72309b1e421a5399f9f6a426e5fe/src/ploomber/jupyter/manager.py#L185

then add a condition to such iteration logic to ignore tasks if they're not of the `ploomber.tasks.NotebookRunner` class

**Comment by fferegrino** [comment]
Is there a particular reason you don't want to offer support for functions?

**Comment by edublancas** [comment]
It's mostly a resources problem, I'd love to support functions.

`jupyter/manager.py` has the code for the Jupyter plug-in. For notebook and script tasks, this implements the "cell injection" logic ([documented  here](https://ploomber.readthedocs.io/en/latest/get-started/basic-concepts.html#tasks-scripts-notebooks)). 

In the function's case, we cannot implement the cell injection integration because a function is defined in a single cell, so I explored an experimental feature that turns a function definition like this:

```python
def some_function():
    some_code()

   more_code()
```

Into a notebook like this:

```python

# first cell
some_code()

# second cell
more_code()
```

So users can develop functions interactively but they're really editing a function. Unfortunately, there are many edge cases to make this work.

At the moment, the Jupyter integration limits to scripts and notebooks, but you can still open the function definitions in Jupyter's text editor.

**Comment by edublancas** [comment]
closing in favor or https://github.com/ploomber/ploomber/issues/879
