### ISSUE TITLE
Add links to cookbook examples to the docs

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#317]
We have a new cookbook section: https://github.com/ploomber/projects/tree/master/cookbook

where we add minimal examples for certain use cases, we should add links to each one on the relevant sections in the docs

**Comment by idomic** [comment]
@tamoghna-dey any luck? You can join the slack and get more support on your first PR

**Comment by iruoma** [comment]
I will like to work on it

**Comment by lfunderburk** [comment]
Working with @iruoma as part of PyCascades

**Comment by edublancas** [comment]
Great! This one is a bit subjective. To get started, check the cookbook section in the docs: https://docs.ploomber.io/en/latest/cookbook/index.html

and see if there are any missing links to examples in this folder: https://github.com/ploomber/projects/tree/master/cookbook

There are other places where it may make sense to link to the cookbook. Most notably, in the Spec API documentation: https://docs.ploomber.io/en/latest/api/spec.html

**Comment by lfunderburk** [comment]
We tried running the setup as the contributing documentation indicates https://github.com/ploomber/ploomber/blob/master/CONTRIBUTING.md

but when we tried to build the docs we got a message `No module named ploomber`

**Comment by lfunderburk** [comment]
Installing ploomber manually. Should we create an issue to modify the setup.py file?

**Comment by edublancas** [comment]
The problem may be the environment. after running the instructions. did you activate the environment?

**Comment by edublancas** [comment]
please share the commands that you ran

**Comment by lfunderburk** [comment]
Created virtual environment with pip

`python -m venv ploomb-venv`

`.\ploomb-venv\Scripts\activate` (Windows)

`pip install invoke`

`invoke setup-pip --doc`

It finished without errors. But when we tried 

`invoke docs`

We got `No module named ploomber`

We installed ploomber manually via `pip install ploomber`, the rebuild the docs. It worked.

**Comment by edublancas** [comment]
alright, glad you work it working
