### ISSUE TITLE
How to pass raw data to a task via pipeline.yaml?

### ISSUE THREAD

**Issue by rdmolony** [ploomber/ploomber#324]
From: https://app.slack.com/client/T016HTQ4NR3/C028KJCJDRT/thread/C028KJCJDRT-1630597605.003800

> Rowan: I’m playing with ploomber right now and have a raw data file required to run a notebook in the pipeline. Looking at the spec api (very helpful) it looks like tasks.params will let me inject the file path. Ploomber also has a validation check right? how to link the check to a parameter… I could upload to s3 instead as req a manual uploaded file is bad practice anyway, just curious how it works! 

> Rowan: Found it! on_finish

> Rowan: I could have a task to check the file exists and then pass the file path as a parameter to the req task 

> Eduardo: so if the file exists: you want the pipeline to run. if it doesn't: throw an error saying it doesnt exist?

> Rowan: Sure, and also I want to pass the file path to a notebook from pipeline.yaml

> Eduardo: Ok. I'd do it in the same task (as opposed to one that checks if it exists and another one that uses it). as you said, you can use task.params to pass the path to the file (note that relative paths are so to pipeline.yaml  parent folder). then, at the beginning of the notebook task, check if the file exists, if it doesn't raise an error

> Eduardo: unless there's another reason why you want them to be 2 tasks instead of 1

**Comment by rdmolony** [comment]
Solved codema-dev/projects#97

**Comment by rdmolony** [comment]
I found that passing raw data as a parameter to be problematic.  When ploomber renders a python script into a jupyter notebook, it doesn't recognise that it also needs to convert the param filepath.  I created a new task to validate that the raw data has been uploaded, set its output to the uploaded file path and set it as a depenency at dev/projects@ff550ff40b8e103a469c4372667a5314a6a58332

**Comment by edublancas** [comment]
Sounds good. If you need to make some kind of verification (like what you do to check if the file has been uploaded) it's ok to add a new task. If you only need to ensure the param is recognized as a path, you can do this:


```yaml
tasks:
    - source: some.task
       params:
           some_param: '{{here}}/data.csv'
```

`{{here}}` is a placeholder that is expanded to the parent directory of the `pipeline.yaml` file.

**Comment by rdmolony** [comment]
Cool, thanks Eduardo, the jinja templating is a handy fix
