### ISSUE TITLE
Ploomber unnecessarily unserializes unused outputs

### ISSUE THREAD

**Issue by lunik1** [ploomber/ploomber#328]
If a pipeline step is using `serializer`/`unserializer` and defines multiple products, any subsequent step using any of that step's products will unserialize _all_ of the products, rather than just the product(s) used. This requires writing unserializers that may never be needed and inefficiency by unserlialzing unused data.

Example: if pipeline A step produces `data: data.parquet` and `report: report.txt` and pipeline step B uses `upstream["A"]["report"]` both `data.parquet` and `report.txt` will be unserialized, but only `data.parquet` is ever used.

**Comment by edublancas** [comment]
closing in favor of https://github.com/ploomber/ploomber/issues/1097
