### ISSUE TITLE
"ploomber install" should add venv directory to .gitignore

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#330]
(Also create .gitignore if it doesn't exist)

`pip install` automates dependency installation and creating lock files. When using pip, the command first creates a venv in the current directory, such directory must be added to .gitignore to prevent it from being committed.

https://github.com/ploomber/ploomber/blob/ac915ea998f4da0177204f2189f8f608f3404fc6/src/ploomber/cli/install.py#L83

**Comment by Qiwen-Yu** [comment]
I can take this one.
And I'm wondering does this line fix this issue already?https://github.com/ploomber/ploomber/blob/ac915ea998f4da0177204f2189f8f608f3404fc6/src/ploomber/cli/install.py#L85

**Comment by edublancas** [comment]
Ah, good catch. yes! But I noticed the current code would cause duplicates if `.gitignore` already has the `venv-{something}` entry. can you modify the code so it checks the gitignore first and only adds the line if it doesn't exist? and please also remove the `# TODO` comment

**Comment by edublancas** [comment]
sure, apologies. I thought you couldn't find the time to work on this

**Comment by edublancas** [comment]
np, ping me if you need help :)

**Comment by Qiwen-Yu** [comment]
@edublancas I have made the change and tested with my unitest.
