### ISSUE TITLE
[feature] add checkpoints/status.update() for long running tasks 

### ISSUE THREAD

**Issue by chris-aeviator** [ploomber/ploomber#335]
## Description

When using ploomber for long running tasks it would be benefitial to the user if we could update the tasks status incrementally.

## Example

I'm running a prediction pipeline with ploomber that queries a large transformer language model on each line of a `.jsonl` file. Each prediction takes about 60-80 seconds, and I'm running typically around 20 predictions in a single ploomber task.

## Desired 

Rather than having the `ploomber build` command having the percentage of the build stuck at [x]% for my long running task I'd like to update the ploomber status.

## Proposal

add a `status.update(steps_done,total_steps)` method for a task to manually handle it's state

 (also useful for debugging when running ploomber builds in the context of an upstream pipeline system. this would help to find out upstream at what point a long running task errored without relying on task logs )

## Screenshots

So what I'm trying to improve is that the `ploomber build` status stays at 25% for my 20 min long task. It should rather climb incrementally whenever I call `status.update(steps_done=2, steps_total=20)`. This in turn then would also give me an update on estimated time of completion.

![image](https://user-images.githubusercontent.com/11522213/132941309-4bbbe49b-cadd-44f5-a97b-d0e282f80e79.png)

**Comment by edublancas** [comment]
Hi @chris-aeviator, thanks for your feedback!

This is an interesting proposal, although the implementation requires some important changes given the different scenarios where tasks can run: a function in a child process (the default), a function in the same process, or a script/notebook in a separate process (jupyter kernel). But I agree that this would be a great way to track progress.

For the time being, why not using logs? Similar questions have arisen in the past and I've recommended users to log progress, even though the percentage would be static, log records are still useful to track progress of long-running tasks:

```
Building task 'function_log':  75%|███████████████████████████████████████             | 3/4 [00:15<00:05,  5.33s/it]
INFO:tasks:[function log] Finished step 1...
INFO:tasks:[function log] Finished step 2...
INFO:tasks:[function log] Finished step 3...
INFO:tasks:[function log] Done.
```

Any disadvantages you see with this approach?

**Comment by chris-aeviator** [comment]
Thanks for your reply - I'm using logs in the notebook and as products, making this issue was more for the record that if you find this useful it can stay as a feature idea (unti eventually implemented)

**Comment by edublancas** [comment]
Awesome! Thanks for your feedback!

In case you are not there yet, feel free to join the [Slack community](http://community.ploomber.io/), we use it as a casual communication channel for feedback and answering questions.

Also, I just added a [logging](https://ploomber.readthedocs.io/en/latest/user-guide/logging.html) tutorial to the docs.
