### ISSUE TITLE
Tasks with a variable number of outputs

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#339]
We don't have good support for tasks that generate a variable number of outputs (e.g., a folder of images whose number of files depends on certain runtime conditions).

**Comment by lunik1** [comment]
Sounds sensible to me. Perhaps instead of specifying `product: null` explicitly it could be assumed if `product` is omitted? Also what about the case where a task generates a variable number of outputs but also some known, fixed outputs. e.g. a feature selection task that plots the selected features (variable), but also saves the data including only the selected features (fixed).

**Comment by rdmolony** [comment]
This would be really useful, I had this issue today where I read tables from a HTML file I wanted the task to determine the table (see [codema-dev/projects/convert-cso-gas-consumption-from-html-to-csv](https://github.com/codema-dev/projects/tree/main/convert-cso-gas-consumption-from-html-to-csv))

**Comment by edublancas** [comment]
Thanks for your comments @lunik1 and @rdmolony! I'll work on this in the next few days!

**Comment by edublancas** [comment]
Hey @lunik1: I've been thinking of the use case you mentioned (some fixed outputs, some variable outputs). I have an idea of how this may look like. Will update this issue once I have the first implementation.

**Comment by edublancas** [comment]
Hi,

I pushed changes to the master branch. Here's a summary of the new things.

* Docs now have [a section](https://ploomber.readthedocs.io/en/latest/user-guide/faq_index.html#how-do-i-specify-a-task-with-a-variable-number-of-outputs) that explains how to deal with tasks that have a variable number of outputs (includes an example when using serializers)
* Docs now [include a section](https://ploomber.readthedocs.io/en/latest/cookbook/serialization.html) to quickly explain serialization with a link to the new example on using serialization + tasks with variable outputs

@rdmolony: [check out this example.](https://github.com/ploomber/projects/tree/master/cookbook/variable-number-of-products/basic) I think this one is applicable to your use case, but let me know if there are any questions.

@lunik1: [check out this example](https://github.com/ploomber/projects/tree/master/cookbook/variable-number-of-products/serializer). I added an `unpack` argument to the serializer/unserializer decorators to handle the use case. To make it work, you have to install from github (`pip install git+https://github.com/ploomber/ploomber`). Let me know what you think.

**Comment by rdmolony** [comment]
Great, thanks a lot

**Comment by edublancas** [comment]
Closing this, this will be part of the next release (0.13.1)
