### ISSUE TITLE
Add native support for .env

### ISSUE THREAD

**Issue by rdmolony** [ploomber/ploomber#340]
Hi there, I noticed that `pipenv` natively supports reading environmental variables from a `.env` file using [python-dotenv](https://github.com/theskumar/python-dotenv).  It's a really useful library for loading things like s3 credentials, and also easily added into a `pipeline.yaml` using `on_render` (see #326)

It might be easier again if ploomber detected `.env` files automatically, what do you think?

**Comment by edublancas** [comment]
This is a good point. Let me think about what would be the best approach. We already have something kind of similar (`env.yaml`) and we want to make sure that introducing this doesn't cause confusion. However, `.env` files are sort of a standard so it might be good to support them as well. Happy to hear your suggestions.

**Comment by edublancas** [comment]
we haven't gotten this request from other users, so I'll close this for now
