### ISSUE TITLE
How to parametrize a pipeline on a list via env.yaml?

### ISSUE THREAD

**Issue by rdmolony** [ploomber/ploomber#341]
Hi there,

I have a DataFrame ...
```
|      |   Level |   line_length_m | Type                                 |
|-----:|--------:|----------------:|:-------------------------------------|
| 6581 |      44 |       10605.2   | 220kV Underground Electricity Cables |
| 6582 |      44 |        3320.33  | 220kV Underground Electricity Cables |
| 6583 |      44 |         605.984 | 220kV Underground Electricity Cables |
| 6584 |      44 |         746.345 | 220kV Underground Electricity Cables |
| 6585 |      44 |         823.908 | 220kV Underground Electricity Cables |
```

that I want to parameterize my pipeline via ...

`env.yaml`
```yaml
hv_lines:
  - 38kV Overhead Electricity Lines
  - 38kV Underground Electricity Cables
  - 110kV Overhead Electricity Lines
  - 110kV Underground Electricity Cables
  - 220kV Overhead Electricity Lines
  - 220kV Underground Electricity Cables
```

`pipeline.yaml`
```yaml
...
  - source: tasks.extract_hv_line_length_in_small_area_boundaries
    params:
      line_type: "{{hv_lines}}"
    product: "data/processed/{{hv_lines}}.gpkg"
...
```

... so that I can filter and save subsections of the data (`220kV Underground Electricity Cables`) to different files.

using `ploomber interact` followed by `dag["extract_hv_line_length_in_small_area_boundaries"].debug()` shows `line_type` is:

```python-traceback
"['38kV Overhead Electricity Lines', '38kV Underground Electricity Cables', '110kV Overhead Electricity Lines', '110kV Underground Electricity Cables', '220kV Overhead Electricity Lines', '220kV Underground Electricity Cables']"
```

---

I suspect this might be supported already but your (very helpful) tutorial [here](https://ploomber.readthedocs.io/en/latest/user-guide/parametrized.html) doesn't show this use case!  If so, I'll add it to the docs, if not don't worry about it!  (I can just save the data rather than splitting it :) )

**Comment by edublancas** [comment]
Hi,

This isn't supported. Placeholders (e.g., `{{hv_lines}}`) are meant to be boolean flags, numerical or categorical values that you can switch to run the pipeline under different conditions.

What are the different configurations that you want to use? For example, do you want to run your pipeline per each value in your list?

```yaml
  - 38kV Overhead Electricity Lines
  - 38kV Underground Electricity Cables
  - 110kV Overhead Electricity Lines
  - 110kV Underground Electricity Cables
  - 220kV Overhead Electricity Lines
  - 220kV Underground Electricity Cables
 ```

Or do you want pre-defined subsets?

If it's the former, you may want to take a look at the [grid feature](https://ploomber.readthedocs.io/en/latest/cookbook/grid.html), which can create a task instance per value in the list (if you do that, you can even run tasks in parallel). If it's the latter, you may want to define a categorical variable such as `group` and select the values in your code:

```yaml
  - source: tasks.extract_hv_line_length_in_small_area_boundaries
    params:
      group: "{{group}}"
    product: "data/processed/{{group}}.gpkg"
```

```python
def extract_hv_line_length_in_small_area_boundaries(product, group):
    if group == 'some_value'
        values = []
    elif group == 'another':
        values = []
    else:
       values = []
```
Let me know if this helps

**Comment by edublancas** [comment]
btw, I'm working on a fix already. see #342

**Comment by rdmolony** [comment]
It’s the former, grid is exactly what I need as all I’m doing is saving different files, thanks a lot Eduardo!

**Comment by edublancas** [comment]
Awesome, feel free to re-open this if you have issues with `grid`.
