### ISSUE TITLE
Support collections in env.yaml

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#342]
Users may declare collections such as lists or dictionaries in `env.yaml` and then consume them in the `pipeline.yaml` file via placeholders (e.g., `{{placeholder}}`). However, since we use jinja for the placeholders, they're interpreted as strings, hence a collection such as `[1,2,3]` is passed as a string to the pipeline.

See #341 for an example.

**Comment by edublancas** [comment]
Hey @filipj8, I think this is the problem you encountered already. Can you confirm? I'm working on a fix.

**Comment by rdmolony** [comment]
It’s the former, grid is exactly what I need as all I’m doing is saving different files, thanks a lot Eduardo!

**Comment by edublancas** [comment]
Fixed in e5c310504799807f3c81423a0ac4196bcc830526

**Comment by rdmolony** [comment]
nice fix, thanks a lot Eduardo!
