### ISSUE TITLE
Parametrizing output files/different hyperparameters

### ISSUE THREAD

**Issue by lambdaofgod** [ploomber/ploomber#349]
Is there a suggested way to parametrizing output artifacts?

It seems reasonable to expect that since we have parameters in pipeline.yaml, we might want to call some parts with different hyperparameters, and then for example produce different models according to this.

If not, then am I missing something about ploomber? What do you guys suggest to use for experiment tracking with/on top of ploomber?

**Comment by edublancas** [comment]
Hi, great question!

Yes, you can parametrize pipelines using an `env.yaml` file: https://ploomber.readthedocs.io/en/latest/cookbook/parametrization.html

Then you can switch the parameters (e.g., to switch models)

Now, if you have lots of parameters, you can use `grid` which takes a grid of parameters and generates multiple tasks: https://ploomber.readthedocs.io/en/latest/cookbook/grid.html

I'm working on an in-depth tutorial for `grid` so any feedback is welcome!

Let me know if this answers the question.

**Comment by lambdaofgod** [comment]
Wow, that was fast! Thanks!

**Comment by edublancas** [comment]
We're working on improving the docs, if you find anything unclear. please open an issue!

**Comment by idomic** [comment]
@lambdaofgod also feel free to join our community channels and help improving Ploomber: http://community.ploomber.io/

**Comment by idomic** [comment]
@lambdaofgod can we connect to understand your use case better?
