### ISSUE TITLE
Request for a Binder example that combines Ploomber and Mlflow

### ISSUE THREAD

**Issue by kozo2** [ploomber/ploomber#353]
I'm using Mlflow, but Mlflow doesn't have pipeline functionality.
Therefore, I would like to use a combination of Mlflow and Ploomber.
Can I ask you to create the simple notebook example (with Mlflow+Ploomber) that can be reproduced in Binder?

**Comment by kozo2** [comment]
I'm only guessing experimental tracking.
If it's shown to work with Ploomber, I think that's enough.

**Comment by edublancas** [comment]
I've added the [example here](https://github.com/ploomber/projects/blob/master/mlflow/README.ipynb). Feel free to share any feedback you may have.

**Comment by 99snowleopards** [comment]
hello @edublancas - could you update the link to the example notebook that you share above please, thank you

**Comment by edublancas** [comment]
LOL, I was about to tell you I updated the link! Thanks for the heads up!
