### ISSUE TITLE
create a deepcopy of TaskSpec init params

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#358]
`data`, and `meta` params in the TaskSpec constructor are dictionaries: https://github.com/ploomber/ploomber/blob/c87c60db954f72309b1e421a5399f9f6a426e5fe/src/ploomber/spec/taskspec.py#L166

Since both of them are modified inside the class, we should call `copy.deepcopy` to prevent side-effects outside the class

https://github.com/ploomber/ploomber/blob/master/src/ploomber/spec/taskspec.py#L166

**Comment by Qiwen-Yu** [comment]
@edublancas Can I take this one? Thanks!

**Comment by edublancas** [comment]
sure! please add tests to: https://github.com/ploomber/ploomber/blob/master/tests/spec/test_taskspec.py

feel free to ask any questions!

**Comment by Qiwen-Yu** [comment]
Thanks. I'm going to create the unitest first. Just to make sure I understand the expected behaviors correctly.

**Comment by edublancas** [comment]
sounds good! hint: in Python, you can check if two objects are different using the `is not` operator

e.g.

```python
something = ...
spec = TaskSpec(something=something)
# this should fail right now
assert spec.something is not something
```

**Comment by idomic** [comment]
In addition, you can also join the slack channel where we have the Ploomber community and supporters: http://community.ploomber.io/

**Comment by bibhashthakur** [comment]
@edublancas Assign this to me please.

**Comment by edublancas** [comment]
done!
