### ISSUE TITLE
CSS/HTML fix for top bar in documentation

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#364]
For certain screen width (shorter than a monitor but larger than a phone), the top bar in the docs gets weird:

![Screen Shot 2021-10-15 at 11 43 33](https://user-images.githubusercontent.com/989250/137515655-cce817cc-20ce-4ddd-a2e0-ea5eae3af2a0.png)

Source code: https://github.com/ploomber/ploomber/blob/master/doc/_templates/macros.html

We're using [bootstrap](https://getbootstrap.com/)

**Comment by edublancas** [comment]
let me work on pushing instructions for building the docs locally, will update you once it's up

**Comment by edublancas** [comment]
done, feel free to reach out if you have questions 

https://github.com/ploomber/ploomber/blob/master/doc/CONTRIBUTING.md

**Comment by rehman000** [comment]
Okay @idomic I'll look into this as well. Thanks for the heads up! 👍
