### ISSUE TITLE
HTML - Display youtube videos on a responsive table

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#365]
The videos section in the docs embeds youtube videos one after another: https://ploomber.readthedocs.io/en/latest/videos.html

it'd be better to create a responsive table that displays 2-3 columns and collapses them on mobile, we're using the bootstrap framework so it should be simple to do it

source code: https://github.com/ploomber/ploomber/blob/master/doc/_templates/videos.html

contributing guide: https://github.com/ploomber/ploomber/blob/master/doc/CONTRIBUTING.md

**Comment by Youspeakcubic** [comment]
Could i try fixing this?

**Comment by rehman000** [comment]
I'm open to collaborate on this one as well @idomic. Let me know if any help is needed @Youspeakcubic 👍
