### ISSUE TITLE
HTML/CSS - Fix right bar in docs

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#366]
When opening in a large monitor, the docs display a right bar to move between sections ([example](https://ploomber.readthedocs.io/en/latest/user-guide/deployment.html)):

![Screen Shot 2021-10-15 at 12 24 27](https://user-images.githubusercontent.com/989250/137521183-9d530088-442f-438c-a21e-02748b199175.png)

However, on tablets and phones, we remove that bar. It'd be better to add a button to the top bar to toggle it, just like we do with the left bar (see right button):

![Screen Shot 2021-10-15 at 12 25 33](https://user-images.githubusercontent.com/989250/137521225-e9be7f67-a5a8-4572-bd70-aec0790234ef.png)

source code: https://github.com/ploomber/ploomber/blob/76b2abf78092e6696d9e25e47cefdc1e1589529f/doc/_templates/layout.html#L41

check doc/contributing.md for instructions

**Comment by edublancas** [comment]
@rehman000 we use sphinx, which uses jinja. that's why the similarity with flask :)

**Comment by siddharthmagadum16** [comment]
Can you please reassign me to this task? I'm almost done with this. Sorry for the delay.

**Comment by idomic** [comment]
Unassigned since there was no updates, feel free to submit a PR

**Comment by edublancas** [comment]
we merged the PR https://github.com/ploomber/ploomber/pull/389

**Comment by edublancas** [comment]
I'm re-opening this. I realized we merge this to a dev branch but we never merged to master (because there were a few observations in the PR that were never addressed)

**Comment by e1ha** [comment]
<img width="212" alt="Screen Shot 2022-08-23 at 10 14 23 AM" src="https://user-images.githubusercontent.com/59583520/186222751-a42d6dd8-cb25-40cb-be5e-6355c2555aeb.png">
Is the idea to create a button that will toggle the opening of that side bar?

**Comment by edublancas** [comment]
yes, but we're talking about the right side bar (which shows the sections for the current doc). what you showed is the left one.

the main UX challenge here is that we already have a button on the right (the search button). so please help us brainstorm solutions

**Comment by e1ha** [comment]
How about adding another button next to the current hamburger menu?

**Comment by edublancas** [comment]
yeah, I think it's a decent solution.

the bar would look busy with three buttons but I cannot think of any other solution
