### ISSUE TITLE
JS - Right bar navigation

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#368]
The [docs](https://ploomber.readthedocs.io/en/latest/user-guide/deployment.html) have a right bar that shows the contents of the current article

![Screen Shot 2021-10-15 at 12 24 27](https://user-images.githubusercontent.com/989250/137522983-6d25c30f-db27-462a-b7a0-a74be5b20ee8.png)

The font-weight should change to highlight the current section but it's no longer working, I'm not sure why:

here's the JS code: https://github.com/ploomber/ploomber/blob/master/doc/_static/js/custom.js

check out doc/contributing.md for details

**Comment by MalevolentStrix** [comment]
> Sure. If you have question, you can ping us on Slack http://community.ploomber.io/

Thank you, I'm joining it right now.

**Comment by edublancas** [comment]
if you want to build the docs locally, check out the contributing guide https://github.com/ploomber/ploomber/blob/master/doc/CONTRIBUTING.md

**Comment by MalevolentStrix** [comment]
> if you want to build the docs locally, check out the contributing guide https://github.com/ploomber/ploomber/blob/master/doc/CONTRIBUTING.md

Yeah, I have completed the build, hopping into the solving process.
![image](https://user-images.githubusercontent.com/73242397/137549303-af331dc4-afe7-481d-9bdd-e0ef061460cc.png)

**Comment by edublancas** [comment]
hey @MalevolentStrix, we closed this already, but since you made some progress building the docs. you may choose an of the other doc-related issues.
