### ISSUE TITLE
Fix broken links in doc

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#376]
The doc/ directory contains our documentation. Some files there link to our [projects](https://github.com/ploomber/projects) repo, however, we're rolling out a folder layout change soon, which you can see by going to the [layout branch](https://github.com/ploomber/projects/tree/layout)

To avoid confusion: this issue is about fixing links on this repo that point to https://github.com/ploomber/projects

Example:

`spec-api-python` in the master branch, becomes `guides/spec-api-python` in the layout branch.

We need help updating those links, essentially we need to look for links containing `https://github.com/ploomber/projects/tree/master` then update the last part to match the new layout.

e.g.

`https://github.com/ploomber/projects/tree/master/spec-api-python`

becomes

`https://github.com/ploomber/projects/tree/master/guides/spec-api-python`

Here's an example of a file that needs an update: https://github.com/ploomber/ploomber/blob/master/doc/cookbook/grid.rst

note that the last link is: https://github.com/ploomber/projects/blob/master/mlflow/README.ipynb

However `mlflow` ([master branch)](https://github.com/ploomber/projects/tree/master/mlflow) moved to `templates/mlflow` ([layout branch)](https://github.com/ploomber/projects/tree/layout/templates/mlflow)

**Comment by Himanshu664** [comment]
@edublancas I would like to work please assign

**Comment by edublancas** [comment]
Awesome! Feel free to [send us a message](http://community.ploomber.io/) if you need help

**Comment by jennifertieuu** [comment]
Hi @edublancas , this is my first time contributing to open source and I found this project on the project-sharing channel in the Hacktoberfest Discord. If this issue is still open, can I be assigned to it? Thank you!

**Comment by edublancas** [comment]
Awesome! Thanks for choosing Ploomber for your first contribution :) If you have questions, feel free to [send us a message.](http://community.ploomber.io/)

**Comment by jashlodhavia** [comment]
Hey, let me know if this issue is still open, I will close it asap

**Comment by ooliver1** [comment]
Damn it's taken a few hours for those guys
