### ISSUE TITLE
invoke setup may break due to psycopg2

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#386]

**Comment by edublancas** [comment]
alright, this is how we can help users:

here: https://github.com/ploomber/ploomber/blob/e8c8331af7f3d375a0f592aa3f4187d666724522/tasks.py#L53

we run the setup command. this is the one that may fail. so we can catch errors there and print some helpful message:

```python
    try:
        c.run(' && '.join(cmds)) 
    except Exception as e:
        print(
            'Failed to run invoke setup. Have issues with psycopg2? Remove from setup.py and try again.'
        )
        raise
```

the same applies to this: https://github.com/ploomber/ploomber/blob/e8c8331af7f3d375a0f592aa3f4187d666724522/tasks.py#L76

**Comment by tammytdo** [comment]
I will work on this
