### ISSUE TITLE
Improve pipeline plot

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#393]
The output plot is pretty boring:

![index](https://user-images.githubusercontent.com/989250/138205596-bc314e8d-eecb-4137-b922-41b954db5bbf.png)

We're using pygraphviz to generate it and it has lots of customization options to make it better.

Here's the code that generates the plot:

https://github.com/ploomber/ploomber/blob/068df147c2c9af0f998beb6128e13fffe16e86e3/src/ploomber/dag/dag.py#L787

https://github.com/ploomber/ploomber/blob/f6013f9b21ae644976c1696b1d989968d1042602/src/ploomber/dag/dag.py#L820

The fix involves checking the options we have in https://graphviz.org/ to make the plot prettier

To get started, you can clone one example and generate one plot: https://docs.ploomber.io/en/latest/user-guide/templates.html

one option we should have is to only show task names (hide products)

- [x] option to hide products
- [x] document option to hide products in the .rst docs
- [x] improve the plot style (colors, font size, etc)

**Comment by edublancas** [comment]
Yes! I'd really appreciate it! Feel free to [reach out to us on Slack](http://community.ploomber.io/) if you have questions. And please show your support with a star :)

Check out our [contributing guide](https://github.com/ploomber/ploomber/blob/master/CONTRIBUTING.md) to get started.

**Comment by idomic** [comment]
@seakyith any updates there?
In a few days this will be reassigned.

**Comment by idomic** [comment]
@fferegrino wanna take a look?
