### ISSUE TITLE
Introduce Thoth jupyterlab-requirements for reproducible notebooks and pipelines.

### ISSUE THREAD

**Issue by pacospace** [ploomber/ploomber#413]
Project Thoth [1] uses Artificial Intelligence to analyze and recommend software stacks for Python applications optimized for their specific environment and recommendation (software stack provided as `Pipfile, Pipfile.lock` format as supported by `pypa` https://pipenv.pypa.io/en/latest/). Thoth wants to help developers (including data scientists) to manage dependency easily, allowing them to state their requirements and gurantee reproducibility and shareability of their projects.

Project Thoth [1] has several integrations: 
- CLI/library integration called `thamos` [2] to handle any action with `.thoth.yaml` and interaction with Thoth service.
- JupyterLab Notebooks integration called `jupyterlab-requirements` [3] in order to make them reproducible and shareable: https://github.com/thoth-station/jupyterlab-requirements#usage. This could help also tools like repo2docker to identify the pinned-down software stack coming with a certain notebook.
- S2I integration [4].
- Github App [5]

For this feature request, I would focus on `jupyterlab-requirements library` [3]. 
Even though many developers (including data scientists) focus on their core problems when working on their experiments, there is one aspect that can make these projects not reusable. One of the first steps during the development of a project is the `selection of libraries or dependencies`. When someone runs `pip install <package-name>`, they might not be aware that along with the library that is going to be installed, a direct dependency, many other dependencies will be installed on your machine, so called transitive dependencies. Any change in one of those dependencies can break your experiment. It's fundamental to have a way to state all the dependencies used, including the operating system, python interpreter and hardware that was used to run a certain experiment.

Dependency management is one of the most important requirements for reproducibility. Having dependencies clearly stated allows portability of notebooks, so they can be shared safely with others, reused in other projects or simply reproduced. If you want to know more about this issue in the data science domain, have a look at this [article](https://developers.redhat.com/blog/2021/03/19/managing-python-dependencies-with-the-thoth-jupyterlab-extension/) or this [video](https://www.youtube.com/watch?v=ifyQ2oSxjnU).

### References
- [1] https://thoth-station.ninja/
- [2] https://github.com/thoth-station/thamos
- [3] https://github.com/thoth-station/jupyterlab-requirements
- [4] https://github.com/thoth-station/s2i-thoth
- [5] https://github.com/marketplace/khebhut

**Comment by edublancas** [comment]
thanks for sharing this, I'll look into it!
