### ISSUE TITLE
Better feedback in Jupyter when failing to load the pipeline

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#415]
we only display feedback to the Jupyter console

**Comment by edublancas** [comment]
this is actually pretty hard to implement 👀 i did some quick prototyping

**Comment by idomic** [comment]
Is this still unresolved?

**Comment by edublancas** [comment]
yes

**Comment by edublancas** [comment]
closing this in favor of https://github.com/ploomber/ploomber/issues/896
