### ISSUE TITLE
Better support for non-Jupyter editors like VSCode or PyCharm

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#416]
the cell injection process only works on Jupyter

**Comment by edublancas** [comment]
Interesting, thanks for sharing! I have to run a few experiments to see what's the best solution.

**Comment by idomic** [comment]
@edublancas I think we can close this issue now that we have the new integration?
@ajasja make sure to go over this guide: https://docs.ploomber.io/en/latest/user-guide/editors.html
We'll probably add a new example soon

**Comment by edublancas** [comment]
Yep
