### ISSUE TITLE
Support for MATLAB scripts

### ISSUE THREAD

**Issue by s10singh97** [ploomber/ploomber#421]
Hi,

I have been working on some personal project which requires me to initially retrieve data from Wifi NIC and  preprocess data in MATLAB before storing the data and continuing the analysis in Python. It would be great if you could add support to include MATLAB scripts in the pipeline.

Thanks!

**Comment by idomic** [comment]
Thanks @s10singh97 
What about running those scripts through shell?
Something like that? https://stackoverflow.com/questions/38723138/matlab-execute-script-from-command-linux-line

We do have this integration with shell and I think that's a pretty good option if the Matlab script is in its final form. Does it solve the issue for your use case?

**Comment by edublancas** [comment]
Yes, as Ido mentioned. You could run it as a shell script. I just realized we don't have an example that has .sh files so if this solves your problem, I can quickly put together an example

**Comment by s10singh97** [comment]
Thanks @edublancas and @idomic ! Yes, this works for me. It would be great if you could add an example as well.

**Comment by edublancas** [comment]
Hi @s10singh97, I put together a short example that has [shell scripts as tasks](https://github.com/ploomber/projects/tree/master/templates/shell).

Note that for this example to serve your use case, you need to make your Matlab script take arguments:

```sh
matlab test.m path/to/output
```

I made a small change to the library to improve the experience, so make sure you upgrade `pip install ploomber --upgrade`.


I think the current implementation should work but let me know if you have any issues (e.g., getting some `matlab command not found` error or something like that when running the pipeline)

**Comment by s10singh97** [comment]
Thanks @edublancas ! This solves my purpose. I am able to run matlab scripts though this.

**Comment by edublancas** [comment]
Awesome! Feel to open another issue if you encounter any problems. And consider joining our community to keep in touch: https://ploomber.io/community

**Comment by edublancas** [comment]
Hey @s10singh97 , we just added a new guide that shows how to run tasks in any programming language, it contains a few tips to streamline the experience. let me know what you think https://ploomber.readthedocs.io/en/latest/user-guide/shell.html
