### ISSUE TITLE
Update docs to show how to configure JupyterLab to open .py files as notebooks with a single click

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#427]
This is now possible with the latest version of jupytext https://github.com/mwouts/jupytext/issues/271#issuecomment-982181041

**Comment by idomic** [comment]
@arturomf94 want to take this?

**Comment by arturomf94** [comment]
Of course 👍  In which part of the docs would we want this to be?

**Comment by edublancas** [comment]
Thanks, @arturomf94 for your help!

The change should go here: https://github.com/ploomber/ploomber/blob/master/doc/user-guide/jupyter.rst

I'm thinking of adding a new section at the end of the document explaining how to enable this: which jupytext version required + the steps to enable it, then add a link next to this text:

> When using jupyter notebook, scripts automatically render as notebooks. If using jupyter lab: Right-click -> Open With -> Notebook as depicted below:

to tell users that if they want to enable this feature, they should follow the instructions in the new section

**Comment by arturomf94** [comment]
> Thanks, @arturomf94 for your help!
> 
> The change should go here: https://github.com/ploomber/ploomber/blob/master/doc/user-guide/jupyter.rst
> 
> I'm thinking lets add a new section at the end of the document explaining how to enable this: which jupytext version required + the steps to enable it, then add a link next to this text:
> 
> > When using jupyter notebook, scripts automatically render as notebooks. If using jupyter lab: Right-click -> Open With -> Notebook as depicted below:
> 
> to tell users that if they want to enable this feature, they should follow the instructions in the new section

@edublancas - thanks! sorry for the delay... i took some days off but now i'm back :) will get down to work on this during the week! 👍

**Comment by edublancas** [comment]
No worries, thanks a lot!
