### ISSUE TITLE
Warn on large files when using resources_

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#429]
Users can tell Ploomber to track changes to configuration files via [resources_](https://ploomber.readthedocs.io/en/latest/api/spec.html?highlight=resources_#tasks-params-resources), however, to track changes, we compute a file hash which may take too long if the file is large.

We should show a warning if this happens, `resources_` should not be used with large files.

**Comment by edublancas** [comment]
the fix involves checking the file size of tasks passed in the `resources_` key (see link in the original comment for an example), to check files, use this: https://docs.python.org/3/library/stat.html

if any file is above some threshold (say >1MB), then we should [the warnings module](https://docs.python.org/3/library/warnings.html) to alert the user that the file is too big

**Comment by Vinay26k** [comment]
Hi, please assign this issue to me. I will give it a try.

**Comment by edublancas** [comment]
sure!

**Comment by edublancas** [comment]
closed by #609
