### ISSUE TITLE
Function to clean (delete) output files

### ISSUE THREAD

**Issue by ajasja** [ploomber/ploomber#431]
Sometimes the output files take up a lot of space or are no longer necessary.
I analogy to `make clean` I propose a function to delete the output files.

`ploomber clean `
`ploomber clean {taskname}`

**Comment by edublancas** [comment]
Thanks for your feedback!

I think from Python should be something like:

```python
dag.clean()
dag['task'].clean()
```

(and delete existing products + metadata)

From the CLI, I'm still unsure if it should be:

```sh
ploomber task {name} --clean
```

or

```sh
ploomber clean {name}
```


Note to self: should this delete remote copies if a client is configured?
