### ISSUE TITLE
Detect when tests create files in the current working directory

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#442]
Many tests have to create files to work (e.g., create a `pipeline.yaml`) file. To isolate tests, we have a `tmp_directory` fixture that creates a temporary directory, moves the test to that directory, runs the text, cleans up the directory and goes back to the original working directory.

However, if a new test is included and the author forgets to include the `tmp_directory` fixture, and creates some files, it may contaminate the environment and break other tests.

I think a good way to solve it is to have a pytest fixture that should run every time and checks that no files were created outside a temp directory by the current test.

Another alternative is to have an `autouse=True` fixture that always creates a temporary directory, but this might have an performance impact (although I don't think this will be important), and it might break tests that require to be executed in certain locations

**Comment by fferegrino** [comment]
Happy to look into this, and I would argue we need something similar but for modules.

**Comment by edublancas** [comment]
Sure, thanks!

I'm thinking of some pytest fixture that uses the autouse flag, and checks if we're in a non-tmp directory (I think we can check this by checking if the current directory has a `tmp` component, if so, check if the files changed between the start of the test and the end of it, if so, raise an exception.

How would that apply to modules? Do you mean testing modules?
