### ISSUE TITLE
Adjusting docs links

### ISSUE THREAD

**Issue by idomichael** [ploomber/ploomber#443]
Since we changed the domain of the docs to docs.ploomber.io 
We need to search in all of our repos: ploomber, soorgeon, soopervisor and projects:
Look for the ploomber.readthedocs.io address and replace it with docs.ploomber.io

Please follow the contribution guildelines for the docs.

**Comment by jramirez857** [comment]
I would like to work on this. Should this come as 4 different pull requests for each repo? Do the other repos have their own issue?

**Comment by edublancas** [comment]
hey @jramirez857, thanks for taking this one! 

I'm not sure which repos still have old links, so this is a bit of detective work. The rest of the repos don't have open issues on this, but feel free to open PRs over there if you find any outdated links.

**Comment by DataCascadia** [comment]
woud grep work to find all files with that string?

**Comment by edublancas** [comment]
Thanks for your PR, @jramirez857 

@DataCascadia: yes, grep should work. although I'm not sure if there are any left links on this repo since @jramirez857 submitted a PR to fix it.

**Comment by jramirez857** [comment]
I have updated the links I found across the ploomber, soorgeon and projects repos. I searched soopervisor as well and did not find any links.

**Comment by edublancas** [comment]
awesome, closing this
