### ISSUE TITLE
Tasks cannot create sub-processes when run as subprocesses

### ISSUE THREAD

**Issue by lunik1** [ploomber/ploomber#447]
In Python a process cannot create a sub-process if it is a sub-process (see [here](https://github.com/python/cpython/blob/c2ac4cf040ea950bf552d1e77bea613a1a5474fe/Lib/multiprocessing/process.py#L118)). As Ploomber runs tasks in sub-processes by default when using `ploomber build` tasks that spawn subprocesses, such as [auto-sklearn](https://github.com/automl/auto-sklearn), will fail.

This can be fixed using Ploomber's Python API by setting the executor with
```
dag.executor = Serial(build_in_subprocess=False)
```
however this is not currently exposed in the yaml configuratiuon.

**Comment by edublancas** [comment]
Thanks for reporting this. I fixed it, this will be part of the next release (coming out in the next few days)

**Comment by edublancas** [comment]
forgot to post the documentation link: https://docs.ploomber.io/en/latest/api/spec.html#executor
