### ISSUE TITLE
SQLUpload io_handler API confusion

### ISSUE THREAD

**Issue by johnseq-iterative** [ploomber/ploomber#448]
The `SQLUpload` task takes a parameter `io_handler` that can be used to run custom code and return a dataframe in the event you need custom processing.

Currently the `run` method of SQLUpload checks for `io_handler` but doesn't do anything with it.

The code should probably look like this:

```
        if self.io_handler is None:
            extension = Path(path).suffix
            read_fn = mapping.get(extension)

            if not read_fn:
                raise ValueError(
                    'Could not infer reading function for '
                    'file with extension: {}'.format(extension),
                    'pass the function directly in the '
                    'io_handler argument')
        else:
            read_fn = self.io_handler
```

**Comment by edublancas** [comment]
Thanks for reporting this! It's fixed now, this will be part of the next release (coming up in the next few days)
