### ISSUE TITLE
GCP AI Platform Jobs integration

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#458]
We need to create a similar integration + tutorial to this one we have with AWS Batch: https://soopervisor.readthedocs.io/en/latest/tutorials/aws-batch.html

The story is about:
Integrating the client with GCP AI Platform Jobs functionality.
Creating a tutorial similar to the one above.
If possible create a short video to guide through the tutorial

**Comment by edublancas** [comment]
no longer a priority, closing this. feel free to open if you think we should work on this
