### ISSUE TITLE
ploomber nb hides traceback if pipeline fails to load

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#468]
If the pipeline cannot load, the error is as follows:

```
Error: Could not run nb command: the DAG failed to load
```

However, when using another command such as `ploomber status`, the traceback is displayed.

**Comment by idomic** [comment]
@arturomf94 want to take a look here?

**Comment by edublancas** [comment]
fixed by 343006e8f2701ff52d0f1f8a8e823d35f69ab613
