### ISSUE TITLE
CI - running versions independent 

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#470]
When running the CI, those version tasks should run independently from each other. When we have a failing CI we can re-run but it runs all of the os versions, for instance, we'll need to run MacOS, v 3.6,7,8,9. Ideally those will be segregated. The files we're looking at are under this location: .github/workflows/ci-mac.yml

**Comment by idomic** [comment]
A bit more context, saving the job status in the end and loading it in the beginning will solve this (workaround): https://github.com/jaredpalmer/razzle/blob/f8305c26997bae8ef0f5dfa52540d842451b4090/.github/workflows/examples.yml .

In addition there's an open issue about this topic, maybe it'll happen in Q1 22' https://github.com/actions/runner/issues/432

**Comment by edublancas** [comment]
this has been recently added to Actions, closing this
