### ISSUE TITLE
compatibility with IPython 8

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#479]
IPython just had a major release and one of the tests is breaking so I pinned the version in `setup.py`. Ploomber actually works fine, it seems like some of the testing config is incompatible with the new IPython internals.

Even a diagnosis of next steps will be useful here!

**Comment by idomic** [comment]
@edublancas was this the test that was failing?
@yafimvo try exploring what's needed to fix this test

**Comment by edublancas** [comment]
I dont remember which test was failing when I tried it
