### ISSUE TITLE
Allow positional argument in ploomber scaffold

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#484]
```
ploomber scaffold mynewproject
```

Note: since this requires an update to `ploomber-scaffold`, we'll have to release that first, then pin the version here

**Comment by idomic** [comment]
@lgfunderburk this can be a good issue for you to tackle

**Comment by edublancas** [comment]
The scaffold logic is here: https://github.com/ploomber/scaffold

So we need two PRS one there and one here

**Comment by lgfunderburk** [comment]
Thank you. Taking a peek
