### ISSUE TITLE
Improve warnings management when running ploomber build

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#487]
Sometimes, third-party libraries emit warnings; when ploomber runs a pipeline, it will capture the warnings and show them at the end. 

- [ ] see if we can do something to improve the information displayed to help the user find what library displayed the warning
- [ ] add a way to suppress the warnings. it's possible to not capture them by switching the executor, so maybe add a section in the docs and print  a link it if dag executes with warnings

**Comment by idomic** [comment]
For 2. we probably want to allow the user the level of logging, maybe verbose levels or info/debug/errors only like for logger
