### ISSUE TITLE
improving the onboarding workflow

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#501]
the current onboarding tells the user to download an example, then run `ploomber build` but that's it, after that, we don't provide any feedback.

Notes:
maybe we should ask the user what editor they use. if they use vscode/pycharm, they'll need to manually inject the cell

I think we should have more guidance so they can explore the tool.

Here's an idea:

```python
# launch tutorial
python -m ploomber.tutorial
```

```
Welcome to the ploomber tutorial, run ploomber examples to see what's available
```

```python
ploomber examples
```

```
Great! now select one example
```

```python
ploomber examples -n templates/ml-basic -o output
```

```
Awesome, now move to output/ and execute ploomber build
```

```python
cd output
ploomber build
```

```
You just build your first pipeline!
```

```
Try modifying one of the tasks (for example, edit x.py), then execute ploomber build again
```

We could define exactly what other steps to have (like `ploomber task`, `ploomber plot`)

thoughts? @idomic

**Comment by idomic** [comment]
Yeah I like this flow, I think the first stepping stone should be ploomber refactor + an option to skip to a template example. There should be a mechanism to use an api to track the workflow status/rerun etc later on

**Comment by edublancas** [comment]
note: since we'll be making changes to the .ploomber directory. I think we could use it to keep track of the status. example: know if a user ran their first pipeline, it it hasn't, output a message after the first successful `ploomber build` with next steps (try `ploomber scaffold`, join our community, etc)

**Comment by edublancas** [comment]
this has been implemented
