### ISSUE TITLE
DAG visualization and control mechanism

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#505]
Ideally the DAG can be changed from multiple places and not just via text editor. Some of the users complained on having a mechanism of visualization and a GUI to control the graph.

**Comment by edublancas** [comment]
For inspiration, Elyra has a visual editor: https://github.com/elyra-ai/elyra

Maybe we can re-use some components?

**Comment by edublancas** [comment]
closing in favor of https://github.com/ploomber/ploomber/issues/687
