### ISSUE TITLE
improve error message when pipeline.yaml does not exist

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#509]
If a user runs any ploomber command and passes `-e pipeline.yaml` in a directory that doesn't have such a file, the error isn't very clear:

```sh
ploomber status -e pipeline.yaml
```

```pytb
Traceback (most recent call last):
  File "/Users/Edu/dev/ploomber/src/ploomber/cli/io.py", line 34, in wrapper
    fn(**kwargs)
  File "/Users/Edu/dev/ploomber/src/ploomber/cli/status.py", line 15, in main
    dag, args = parser.load_from_entry_point_arg()
  File "/Users/Edu/dev/ploomber/src/ploomber/cli/parsers.py", line 213, in load_from_entry_point_arg
    entry_point = EntryPoint(self.parse_entry_point_value())
  File "/Users/Edu/dev/ploomber/src/ploomber/entrypoint.py", line 19, in __init__
    self.type = find_entry_point_type(value)
  File "/Users/Edu/dev/ploomber/src/ploomber/entrypoint.py", line 65, in find_entry_point_type
    raise ValueError(
ValueError: Could not determine the entry point type from value: 'pipeline.yaml'. Expected an existing file with extension .yaml or .yml, existing directory, glob-like pattern (i.e., *.py) or dotted path (i.e., module.sub_module.factory_function). Verify your input.
```

It'd be better to check if the argument "looks like" a path to a yaml file, and if so, say that the path doesn't exist. If it doesn't look like a path to a yaml, print the default error message.

**Comment by aadityasinha-dotcom** [comment]
Can I work on this issue?

**Comment by edublancas** [comment]
Sure

**Comment by aadityasinha-dotcom** [comment]
I guess I should add a condition here for yaml file but my question is why the condition `elif '.' in entry_point and Path(entry_point).suffix not in`  is not enough for handling that exception.

```
def try_to_find_entry_point_type(entry_point):
    if entry_point is None:
        return None
    elif '*' in entry_point:
        return EntryPoint.Pattern
    elif '::' in entry_point:
        return EntryPoint.ModulePath
    elif Path(entry_point).exists():
        if Path(entry_point).is_dir():
            return EntryPoint.Directory
        else:
            return EntryPoint.File
    elif '.' in entry_point and Path(entry_point).suffix not in {
            '.yaml', '.yml'
    }:
        return EntryPoint.DottedPath
```

**Comment by edublancas** [comment]
I think it's best to handle this outside that function and do it here:

https://github.com/ploomber/ploomber/blob/5d881857616922be49559bafc5f8b1efa85729b7/src/ploomber/entrypoint.py#L65

so something like this:

```python
    if type_:
        return type_
    else:
        # check if entry_point has the .yaml extension (you can use pathlib.Path)
        # if so, throw the new error, otherwise, throw the existing error

        raise ValueError(
            'Could not determine the entry point type from value: '
            f'{entry_point!r}. Expected '
            'an existing file with extension .yaml or .yml, '
            'existing directory, glob-like pattern '
            '(i.e., *.py) or dotted path '
            '(i.e., module.sub_module.factory_function). Verify your input.')

```

**Comment by aadityasinha-dotcom** [comment]
> I think it's best to handle this outside that function and do it here:
> 
> https://github.com/ploomber/ploomber/blob/5d881857616922be49559bafc5f8b1efa85729b7/src/ploomber/entrypoint.py#L65
> 
> so something like this:
> 
> ```python
>     if type_:
>         return type_
>     else:
>         # check if entry_point has the .yaml extension (you can use pathlib.Path)
>         # if so, throw the new error, otherwise, throw the existing error
> 
>         raise ValueError(
>             'Could not determine the entry point type from value: '
>             f'{entry_point!r}. Expected '
>             'an existing file with extension .yaml or .yml, '
>             'existing directory, glob-like pattern '
>             '(i.e., *.py) or dotted path '
>             '(i.e., module.sub_module.factory_function). Verify your input.')
> ```

Ok, thanks.

**Comment by aadityasinha-dotcom** [comment]
I think this should work.

> 
> ```
> if(Path('my_file.yaml').suffix == '.yaml'):
>             raise Exception("Path does'nt exist")
> ```
