### ISSUE TITLE
add auto-completion to the CLI

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#524]
If someone types:

```
ploomber exa
```

And presses the tab key, it should autocomplete to:

```
ploomber examples
```

**Comment by jramirez857** [comment]
Hello, I would like to try to take this on. I see that [cli.py](https://github.com/ploomber/ploomber/blob/master/src/ploomber/cli/cli.py) uses click for autocompletion. Would this issue involve adding similar functionality to [examples.py](https://github.com/ploomber/ploomber/blob/master/src/ploomber/cli/examples.py)?

**Comment by edublancas** [comment]
this is an interesting issue. yes, we use click for a part CLI, but for other parts, we use `argparse`.

I think click has some auto-completion features: https://click.palletsprojects.com/en/8.0.x/shell-completion/

but I'm not sure how it works, so any improvements would be greatly appreciated!

**Comment by edublancas** [comment]
essentially, if someone types:

```
ploomber e
```

and then presses the tab key, we want to suggest what commands are available

**Comment by Vinay26k** [comment]
Hi, is this still unassigned? I would like to give it a try.

**Comment by idomic** [comment]
@jramirez857 are you still working on it?

**Comment by edublancas** [comment]
There's actually a PR

**Comment by idomichael** [comment]
Yeah I missed it.

**Comment by jramirez857** [comment]
[Updated PR #612](https://github.com/ploomber/ploomber/pull/612)

**Comment by edublancas** [comment]
closed by #612
