### ISSUE TITLE
Error when running the examples command twice

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#534]
The output of such outcome (ploomber examples some_example X2) should be click.echo to the user saying the example is already in the environment + the next step

**Comment by edublancas** [comment]
you mean:

```
ploomber examples -n example -o folder

ploomber examples -n example -o folder
```

?

 I think the problem is that we cannot be sure that `folder` contains the example, it could contain any other thing. I think the current error message is clear: "folder exists, choose another name"

**Comment by idomic** [comment]
Yeah exactly what I meant, is there a situation it breaks in the middle? like the folder is there but empty for instance?
Also if you're happy with the user print solution you can close

**Comment by edublancas** [comment]
It works that way to prevent overwriting files or polluting the user's directory. If will also throw this error even if the directory is empty. I'm not sure how much we should think of this, I think it's fine
