### ISSUE TITLE
replace dependency on pygraphviz

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#540]
`ploomber plot` depends on pygraphviz and graphviz, the latter is not pip-installable which makes setup difficult. we should find a way for users to easily create a dag plot, ideally with no extra dependencies

**Comment by edublancas** [comment]
I did some research on this. According to this [article](https://wimyedema.medium.com/drawing-dags-5cadcb452115), the best non-pygraphviz option is [d3-dag](https://erikbrinkman.github.io/d3-dag/index.html). That could work.

I think we should also implement some text-based representation that does not depend on any external libraries.

**Comment by idomic** [comment]
@Vinay26k this is an easy and an important one you can work on.

**Comment by Vinay26k** [comment]
Sure, assign it to me. I will give it a try.

**Comment by edublancas** [comment]
this involves a bit of research and then the implementation. please share your findings so we are on the same page and we can provide some guidance. thanks a lot for your hard work!

**Comment by idomic** [comment]
Until it's being fixed, if anyone is hitting issues on python < 3.8 this is the way to fix it:
sudo apt-get -qq update -y
sudo apt-get -qq install -y graphviz graphviz-dev
pip -q install graphviz 'pygraphviz<1.8'

**Comment by idomic** [comment]
@Vinay26k any progress here?

**Comment by Vinay26k** [comment]
Hi @idomic, yes started exploring on d3-dag and attached is the output html file rendering generated dynamically through python code. [**WIP**]
![image](https://user-images.githubusercontent.com/22490030/156888858-41e33337-1875-4667-bba7-f6354115e800.png)

**Comment by idomic** [comment]
@Vinay26k This is great!
Is there a way to print the products of the tasks as well? 
Does the colors on the paths mean anything?
Also the color are still indicating the execution status right?

**Comment by edublancas** [comment]
@Vinay26k has been doing great progress. so here are some pointers to incorporate his code into Ploomber:

we'll bundle an HTML template that will be used to generate the DAG, we can put this in the [resources directory](https://github.com/ploomber/ploomber/tree/master/src/ploomber/resources)

I'm thinking that the code to generate the plot should be in a separate module, say `src/ploomber/dag/plot.py`:

```python
# plot.py
def with_d3(dag):
    """Returns an HTML string with the plot, given the DAG
    """
    pass
```

@Vinay26k : I'm guessing you are thinking of using jinja to take the template and generate the output HTML?

Then, we need to integrate this logic into `DAG.plot`. A few notes:

* Currently `DAG.plot` throws an error if `pygraphviz` isn't installed, so we need to remove the `@requires` decorator
* We need another keyword argument called `backend=None`. If None, it should check if pygraphviz is installed (we can use [find_spec](https://docs.python.org/3/library/importlib.html#importlib.util.find_spec) for that). if so, then use pygraphviz as backend, otherwise use the HTML template
* user can also explicitly select a backend by passing `backend='pygraphviz'` or `backend='d3'`
* if  `backend='pygraphviz'`  and pypgrahviz not installed, throw an error

**Comment by idomic** [comment]
@Vinay26k any updates here?

**Comment by Vinay26k** [comment]
Hi @idomic @edublancas, I have drafted a PR and code refactoring is in progress.
Feel free to add your comments if something needs to be updated/ added, while I'm on it.

cli output:
![image](https://user-images.githubusercontent.com/22490030/159134429-865b950e-2ce9-4c58-9d3d-e8ca73d976a8.png)

d3 output:
![image](https://user-images.githubusercontent.com/22490030/159134469-c8b01c66-9bf4-42f8-8bc7-89ea0be657e0.png)

**Comment by edublancas** [comment]
this is amazing! will take a look later
