### ISSUE TITLE
run profiling to determine loading times

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#542]
We need to optimize the time it takes ploomber to load when running 
`ploomber`
or `ploomber --help`

We need to run profiling and see the different load times of the python packages and how we can optimize it to get a faster user response.

**Comment by Sri0027** [comment]
Hi, I am participating in the pycascades sprint. I was checking cProfile library. I am confused as to what is required here. Can you please guide me?

**Comment by edublancas** [comment]
sure. we essentially want to know how we can improve loading time.

if someone runs:

```python
import ploomber
```

It'll take some time to run. because we need to import modules and dependencies. It'd great to know which import statements are causing the most delays so we can optimize accordingly.

So this issue is about discovering what to do. Once we know that, we can open other issues to optimize loading time

should I assign this to you?

**Comment by Sri0027** [comment]
Yes, please.

**Comment by Sri0027** [comment]
Using cProfile, I got the following information on top 10 calls taking most time.
 ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      223    0.008    0.000   14.722    0.066 __init__.py:1(<module>)
   2376/1    0.029    0.000    3.715    3.715 {built-in method builtins.exec}
   2339/1    0.022    0.000    3.715    3.715 <frozen importlib._bootstrap>:986(_find_and_load)
   2331/1    0.013    0.000    3.715    3.715 <frozen importlib._bootstrap>:956(_find_and_load_unlocked)
   2218/1    0.013    0.000    3.714    3.714 <frozen importlib._bootstrap>:650(_load_unlocked)
   2085/1    0.009    0.000    3.714    3.714 <frozen importlib._bootstrap_external>:777(exec_module)
   2755/1    0.003    0.000    3.714    3.714 <frozen importlib._bootstrap>:211(_call_with_frames_removed)
        3    0.000    0.000    3.672    1.224 dag.py:1(<module>)
   790/48    0.003    0.000    3.482    0.073 {built-in method builtins.__import__}
 2423/890    0.005    0.000    1.958    0.002 <frozen importlib._bootstrap>:1017(_handle_fromlist)
 
 On using an import filter, it gives the following.
 
 ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   2339/1    0.022    0.000    3.715    3.715 <frozen importlib._bootstrap>:986(_find_and_load)
   2331/1    0.013    0.000    3.715    3.715 <frozen importlib._bootstrap>:956(_find_and_load_unlocked)
   2218/1    0.013    0.000    3.714    3.714 <frozen importlib._bootstrap>:650(_load_unlocked)
   2085/1    0.009    0.000    3.714    3.714 <frozen importlib._bootstrap_external>:777(exec_module)
   2755/1    0.003    0.000    3.714    3.714 <frozen importlib._bootstrap>:211(_call_with_frames_removed)
   790/48    0.003    0.000    3.482    0.073 {built-in method builtins.__import__}
 2423/890    0.005    0.000    1.958    0.002 <frozen importlib._bootstrap>:1017(_handle_fromlist)
 
 Does this make sense?

**Comment by edublancas** [comment]
this output looks like C-level modules, we'd like more general information. this looks useful: https://pypi.org/project/import-profiler/
