### ISSUE TITLE
module 'mistune' has no attribute 'BlockGrammar'

### ISSUE THREAD

**Issue by mattarderne** [ploomber/ploomber#547]
Installation error following the tutorial at step `ploomber examples -n templates/ml-intermediate`
```
AttributeError: module 'mistune' has no attribute 'BlockGrammar'
```
Fixed with
```
pip install mistune==0.8.4
```

Possibly isolated to my install.

**Comment by edublancas** [comment]
Thanks for reporting this! mistune released a version with breaking API changes.

What pip version are you using? Did you get any warning from pip? We use `nbconvert`, which relies on mistune. `nbconvert` pins a compatible mistune version, but I've seen pip dependency resolver fail sometimes and emit a warning - so probably that happened

**Comment by edublancas** [comment]
Also, if you have any other feedback, [please share it with us.](https://ploomber.io/community)

**Comment by mattarderne** [comment]
Yes got pip warning for `pip 20.2.1` 
That makes sense, thanks!

**Comment by edublancas** [comment]
No problem!
