### ISSUE TITLE
link from videos section to our youtube channel

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#550]
link to our youtube channel (add link at the top)

https://docs.ploomber.io/en/latest/videos.html

```
more videos available in our youtube channel
```

also, if there's a way to add a link that subscribes people, that's grat

**Comment by sagarsadhu** [comment]
Hi @edublancas , I am interested to work on this issue. 

We can try to add a link to subscribe. Please check the below code from url https://developers.google.com/youtube/youtube_subscribe_button

`<script src="https://apis.google.com/js/platform.js"></script>

<div class="g-ytsubscribe" data-channelid="UCaIS5BMlmeNQE4-Gn0xTDXQ" data-layout="full" data-count="default"></div>`

**Comment by edublancas** [comment]
Awesome, please add it to https://github.com/ploomber/ploomber/blob/master/doc/_templates/videos.html

check contributing.md for instructions on building the docs locally
