### ISSUE TITLE
add "rst cheatsheet"

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#552]
many people are new to `.rst` files  - which are the ones we use for the documentation.

we should add a  ".rst cheatsheet" section in doc/contributing.md to show the basics:

what to include:

* how to add external links
* how to add images
* how to add code blocks

look for those here: https://www.sphinx-doc.org/en/master/usage/restructuredtext/

**Comment by lfunderburk** [comment]
Good idea! Can create a cheatsheet

**Comment by lfunderburk** [comment]
Can you assign me @edublancas
