### ISSUE TITLE
Give more visibility to Python API docs

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#563]
Users are having a hard time finding the options available to customize the tasks declared in `pipeline.yaml`.

For example, one user asked how to select a custom kernel to execute a notebook task. The problem is there isn't a good connection between the tutorials and our Python API (people using pipeline.yaml do not directly use the Python API, but that's what powers it under the hood). So a few comments to improve the experience:

- [ ] Tutorials should link to the Python API in relevant cases. example. the [SQL pipelines](https://docs.ploomber.io/en/latest/get-started/sql-pipeline.html) should link to the relevant sections in the [Python API](https://docs.ploomber.io/en/latest/api/python_api.html). We should repeat that for all tutorials

**Comment by idomic** [comment]
@MarcoJHB Wanna take another one?

**Comment by idomic** [comment]
@aadityasinha-dotcom another one :)

**Comment by aadityasinha-dotcom** [comment]
Okay ;)
