### ISSUE TITLE
update documents to reflect new default format

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#564]
initially, we were using the `py:light` format as the default one for scripts:

```python
# +
x = 1

# +
y = 2
```

However, we're now migrating to the percent format to be the default, since VSCode, PyCharm, and others support it:

```python
# %%
x = 1

# %%
y = 2
```

Some sections in our documentation need updates:

https://docs.ploomber.io/en/latest/user-guide/jupyter.html
https://docs.ploomber.io/en/latest/get-started/basic-concepts.html

I found these two but there may be others.

**Comment by idomic** [comment]
@hypefi wanna take a stab at it?
