### ISSUE TITLE
improve error message when deepcopying dag

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#571]
In some situations, the dag object may fail to deepcopy, throwing an uninformative error. we should catch it and show something like: "an error occurred when copying your DAG" 

https://github.com/ploomber/ploomber/blob/afadae033e161090610692bfe4f95e941448ea05/src/ploomber/dag/dag.py#L680

**Comment by idomic** [comment]
@hypefi wanna give this a try?

**Comment by Vinay26k** [comment]
Hi, please assign this issue to me. I will give it a try.

**Comment by edublancas** [comment]
sure!
