### ISSUE TITLE
tip on installing ploomber in the process running jupyterlab

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#573]
[here](https://docs.ploomber.io/en/latest/user-guide/jupyter.html#activating-the-jupyter-extension) we have a big note that explains that the process running jupyter must have ploomber installed (users may only install it in the kernel), but we're missing links from other sections to that one

we should mention that here: https://docs.ploomber.io/en/latest/user-guide/jupyter.html#troubleshooting-pipeline-loading

also, we should link from this section to the troubleshoot section: https://docs.ploomber.io/en/latest/user-guide/jupyter.html#activating-the-jupyter-extension

we should also link from here: https://docs.ploomber.io/en/latest/get-started/basic-concepts.html#the-cell-injection-process to the troubleshooting section

**Comment by idomic** [comment]
@hypefi wanna give it a go?

**Comment by e1ha** [comment]
How should I link the sections to each other?

**Comment by edublancas** [comment]
yes, a link is good enough. just make sure you use restructured text native feature for links (instead of hardcoding URLs):

https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html

**Comment by edublancas** [comment]
@idomic - you assigned this to me but I think you meant adding me as reviewer 😅 add me to the PR once it's open
