### ISSUE TITLE
pygraphviz misspelled in two places

### ISSUE THREAD

**Issue by williewheeler** [ploomber/ploomber#574]
See

https://github.com/ploomber/ploomber/blob/60019786aa0c6ce25a233664d7c1bd6914039271/tests/dag/test_dag.py
https://github.com/ploomber/ploomber/blob/60019786aa0c6ce25a233664d7c1bd6914039271/src/ploomber/dag/dag.py

The library is misspelled as "pypgrahviz".

**Comment by edublancas** [comment]
thanks for reporting this! If you get a chance, it'd be great to have PR :)

**Comment by williewheeler** [comment]
https://github.com/ploomber/ploomber/pull/575

**Comment by edublancas** [comment]
thanks!
