### ISSUE TITLE
regression error: in ploomber build telemetry

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#581]
During the refactoring of the telemetry code, I introduced an error, and we no longer log basic dag info. this code hasn't been released so I'll fix it before the next release

**Comment by edublancas** [comment]
yeah. tests are passing, it's just that we're missing some info to log

**Comment by idomic** [comment]
Maybe we also need to add tests on the output that's not null or no fields
are missing?

**Comment by edublancas** [comment]
yes we should. we had this regression test because we're not testing that we're logging everything we want to

**Comment by edublancas** [comment]
fixed in d2ef3276fad0f871bf2677b7fc592f35b0bd980d
