### ISSUE TITLE
passing custom args to telemetry logging when using the decorator

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#582]
we recently refactored the telemetry to use a decorator, but we now lose the ability to log custom info that is specific to the call

**Comment by idomic** [comment]
We need to make sure that in the new logic of the files we don't lose the uid, or have a mechanism to connect it once there's an upgrade

**Comment by edublancas** [comment]
that's not affected by this (uid)

**Comment by edublancas** [comment]
this has been implemented via the payload argument
