### ISSUE TITLE
Monitoring and alerting on pipelines

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#583]
Some users mentioned the need to log the status of their pipelines. This is especially true when using parameterization and scaling pipelines via the grid (parallel pipelines with different params).
This should have an api call, collect the status of the pipeline and output the pipeline id and its status.

**Comment by edublancas** [comment]
this is cover by the existing monitoring feature, right? can we close this?

**Comment by idomic** [comment]
Yeah this is done
