### ISSUE TITLE
Stats issue: help api is being counted as a ploomber build

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#596]
The -help seems to be not counted as an individual task but as a ploomber build. (4e910212-de2f-4827-abc3-f7a28fc6ca8a)

Scaffold is also a suspect.
version as well.

**Comment by idomic** [comment]
version as well.

**Comment by edublancas** [comment]
the calls are right, the problem is we're modifying sys.argv. see https://github.com/ploomber/ploomber/issues/600

**Comment by idomic** [comment]
Why did we close this? Does this new issue also apply to --version and
scaffold calls?

**Comment by edublancas** [comment]
Yes, all of them
