### ISSUE TITLE
Improve CLI command suggestions

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#618]
We currently have a hardcoded list of strings to catch typos when executing a command: https://github.com/ploomber/ploomber/blob/ff808c83bc63ce8c1ae09b726f0bceeb6d9d786e/src/ploomber/cli/cli.py#L243

However, this isn't robust. pip implements it using difflib, which is part of the standard library:

https://github.com/pypa/pip/blob/5ab7c124db917625e55693773bcc224793d7ceed/src/pip/_internal/commands/help.py

**Comment by aadityasinha-dotcom** [comment]
Can I work on this issue?

**Comment by idomic** [comment]
Yes I don't think Jose started working on it.

**Comment by jramirez857** [comment]
Yes, @aadityasinha-dotcom feel free to take this.

**Comment by aadityasinha-dotcom** [comment]
@edublancas I guess this function will be useful in finding close match to CLI command.
> However, this isn't robust. pip implements it using difflib, which is part of the standard library:

![](https://miro.medium.com/max/626/1*k4xUX9ARfeTWySbbT6DPSA.png)

**Comment by edublancas** [comment]
yes, we want to use that one!
