### ISSUE TITLE
FileExistsError for tasks product specified in pipeline.yaml

### ISSUE THREAD

**Issue by Vinay26k** [ploomber/ploomber#621]
```cmd
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\dev\\python\\contrib\\templates\\ml-basic\\output\\nb.ipynb' -> 'C:\\dev\\python\\contrib\\templates\\ml-basic\\output\\nb.html'
```

**Steps to reproduce:**

1. ploomber build example
2. update `pipeline.yaml` file
    - tasks > product > nb > file.[_extension_]

**Comment by idomic** [comment]
@Vinay26k want to take this one?

**Comment by edublancas** [comment]
this is a duplicate of https://github.com/ploomber/ploomber/issues/333, which we already fix - will be available in the next release
