### ISSUE TITLE
improve error message when missing product key

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#628]
Given a `pipeline.yaml` like this:

```yaml
tasks:
  - source: tasks.get
```

If we execute `ploomber build`, It will fail with this message:

```
Error: Error validating TaskSpec({'source': 'tasks.get', 'upstream': None}). Missing keys: 'product'
```

It'd be better to suggest how to fix it:

```
Error: Error validating TaskSpec({'source': 'tasks.get', 'upstream': None}). Missing keys: 'product'
To fix it:

- source: tasks.get
  product: products/data.csv
```

Note that if this is a script/notebook, the suggested product should have the `nb` key:

```
Error: Error validating TaskSpec({'source': 'tasks.get', 'upstream': None}). Missing keys: 'product'
To fix it:

- source: script.py
  product:
    nb: products/report.ipynb
    data: products/data.csv
```

It is possible (but unlikely) that the DAGSpec is loaded from a dictionary (instead of a `.yaml`) file, in such case the output format of the suggestion should be a dict:

```python
{'source': 'tasks.get', 'product': 'products/data.csv'}
```

**Comment by Ni3dzwi3dz** [comment]
Hi, i`d like to give it a try!

**Comment by idomic** [comment]
Feel free to send a PR, also make sure to go over the Contributing.md.
Thanks for trying to solve it!

**Comment by bstee615** [comment]
I've got a patch for this, I'll submit a PR tomorrow (Hacktoberfest). :smile:

**Comment by edublancas** [comment]
@RodolfoFerro

**Comment by RodolfoFerro** [comment]
@bstee615 Go ahead! 🚀
