### ISSUE TITLE
refactor DAG partial build to use shallow copy

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#645]
`dag.build_partially` uses `deepcopy` internally, however, the DAG may contain references to unserializable objects (this may happen with database clients). I think it's safe to do a shallow copy, so we need to test it and if it's the case, switch the deep copy

**Comment by neelasha23** [comment]
@edublancas 
I tried replacing the deepcopy with shallow copy by adding this method:
```
  def _shallowcopy_safe(self):
      try:
          return copy(self)
      except Exception as e:
          raise RuntimeError(
              "An error occurred while copying DAG object") from e
```

However on running the test_dag.py file the following errors have come up:

```
======================================================================= short test summary info ========================================================================
FAILED tests/dag/test_dag.py::test_build_partially[executor0] - AssertionError: assert {<TaskStatus....: 'executed'>} == {<TaskStatus....ting_render'>}
FAILED tests/dag/test_dag.py::test_build_partially[executor1] - AssertionError: assert {<TaskStatus....: 'executed'>} == {<TaskStatus....ting_render'>}
FAILED tests/dag/test_dag.py::test_build_partially[executor2] - AssertionError: assert {<TaskStatus....: 'executed'>} == {<TaskStatus....ting_render'>}
FAILED tests/dag/test_dag.py::test_build_partially_diff_sessions - KeyError: 'b'
============================================================== 4 failed, 101 passed, 6 warnings in 58.35s ==============================================================
```
I'm a bit stuck on the debugging part. Any suggestions on the next steps regarding the test failures ?

Also, while trying to debugging the issue I found three versions of the touch method all having the same functionality. Is any change required in the touch_root method? :
```
def touch_root(product):
    Path(str(product)).touch()


def touch_root_w_param(product, some_param):
    Path(str(product)).touch()


def touch(upstream, product):
    Path(str(product)).touch()

```

**Comment by edublancas** [comment]
thanks for trying this out! based on the results, it looks like we cannot use a soft copy. so we have to stick with the deep one. Can you open a PR adding a comment on it? So we don't attempt to do a soft copy  in the future :) 

something like "we have to use a deep copy since using a soft one will corrupt task status in subsequent runs"

many thanks for taking a look at this!

**Comment by neelasha23** [comment]
Sure will do that !
