### ISSUE TITLE
Conflicting warning msg - running without a config file

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#651]
When running without a .ploomber/stats/config.yaml this output is showed to the user as a warning but it contains an error string.

/home/admin/miniconda/envs/myenv/lib/python3.9/site-packages/ploomber/telemetry/telemetry.py:329: UserWarning: Error: Can't read config file [Errno 2] No such file or directory: '/home/admin/.ploomber/stats/config.yaml'
warnings.warn(f"Error: Can't read config file {e}")

**Comment by edublancas** [comment]
I think you fixed this, right?

**Comment by idomic** [comment]
Yes
