### ISSUE TITLE
Pipeline can't be run with env file having .yml suffix

### ISSUE THREAD

**Issue by ryparmar** [ploomber/ploomber#659]
### Description
Pipeline can't be run with `env.yml` file. It seems it won't get read at all since variables stated in the `env.yml` are unknown to the pipeline run. Renaming file to `env.yaml` solved the issue for me. 

### Replication
Files for replication of minimal example are attached [here](https://github.com/ploomber/projects/files/8303640/test.zip).

### Task
It would be nice to not be dependent on the suffix. Adjust the code, so it treats `.yaml` and `.yml` suffixes of `env` file equally.

**Comment by idomic** [comment]
@ryparmar thanks for opening this. We'd love to have you on our slack community channel, you can ask questions there and learn more about ploomber: https://ploomber.io/community

**Comment by LawrenceCheng1570** [comment]
Hi @edublancas, thanks for pointing this one out to me! Sorry I would love to, but unfortunately I'm a bit tied up at the moment.
