### ISSUE TITLE
validate import_tasks_from

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#669]
when loading the `import_tasks_from: file.yaml`, we are not validating its contents, if the file is empty, `yaml.safe_load` will return `None`, which will throw a cryptic error message:

https://github.com/ploomber/ploomber/blob/beb625cc977bcd34481608a91daddc5493e0983c/src/ploomber/spec/dagspec.py#L326

Fix:
* If `yaml.safe_load` returns None, replace it with an empty list
* If returns something other than a list, raise an error saying we were expecting a list

**Comment by LawrenceCheng1570** [comment]
Hi! I am new to open source and hoping to contribute. I was wondering if I could try to fix and claim this issue? Thanks!

**Comment by idomic** [comment]
Sure thing, make sure to read the contributing guide!
Feel free to submit a PR

**Comment by edublancas** [comment]
thanks for your interest @LawrenceCheng1570 , here's the contribution guide https://github.com/ploomber/ploomber/blob/master/CONTRIBUTING.md
