### ISSUE TITLE
ploomber plot: RuntimeWarning: Warning: lightgreen is not a known color.

### ISSUE THREAD

**Issue by vgn1** [ploomber/ploomber#671]
I get `RuntimeWarning: Warning: lightgreen is not a known color.` when using `plumber plot`. The graph is drawn but the nodes that are supposed to be green are black instead. It works for the red nodes. I tried this on a regular Python 3.7.5 and a Python 3.7.12 in a conda environment.

```
~/ploomber/guides/first-pipeline$ ploomber plot
Loading pipeline...
100%|████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 12937.40it/s]
/usr/local/lib/python3.7/dist-packages/pygraphviz/agraph.py:1390: RuntimeWarning: Warning: lightgreen is not a known color.

  warnings.warn(b"".join(errors).decode(self.encoding), RuntimeWarning)
Plot saved at: pipeline.png
```

**Comment by vgn1** [comment]
Just realised there's an open issue #539 where you say pygraphviz isn't supported for python 3.7. Closing this.

**Comment by edublancas** [comment]
hey @vgn1, thanks for reporting this. so in #539 we found that to use Python 3.7 or earlier you need a lower version of pygraphviz, can you tell me which version you're using?

```sh
# to check graphviz
dot -V
```

```sh
# to check pygraphviz
python -c 'import pygraphviz; print(pygraphviz.__version__)'
```

My guess is that the colors were introduced in later versions.

**Comment by idomic** [comment]
@vgn1 please let us know if you were able to sort it out?
Also I recommend joining the slack community channel for faster support cycles: https://ploomber.io/community

**Comment by edublancas** [comment]
we replaced the color names with the RGB values (df499d45f76479f563332cf30437a5fc11879e65), hope this solves the issue (I wasn't able to reproduce it)
