### ISSUE TITLE
Better support for PDF reports

### ISSUE THREAD

**Issue by Ro-Ol** [ploomber/ploomber#672]
Hello,

at the moment is only possible to have the report of a task in .ipynb/.html format.
It would also be useful to have them in .pdf.

I personally use wkhtmltopdf for the .html/.pdf conversion, I do not know if it is useful.

Best,
Raffaele

**Comment by idomic** [comment]
So after some digging, you can use .pdf, we're using behind the hood in nbconvert, you'll just need to add more dependencies. You'll need to install pandoc and Tex: https://nbconvert.readthedocs.io/en/latest/install.html#installing-pandoc

Then you can just change the extension to `.pdf`

Let me know if that works for you?

**Comment by edublancas** [comment]
Thanks for your feedback! It makes sense to support different PDF converters, we'll add this to the roadmap. in the meantime, my recommendation is to output `.ipynb` in your `pipeline.yaml` and then convert them to PDF using `nbconvert`

**Comment by Ro-Ol** [comment]
This second approach work, but only if I change

<img src="path/to/Image" width="1000"/>
To
![Name](path/to/Image)
Da: Eduardo Blancas ***@***.***>
Inviato: martedì 22 marzo 2022 15:31
A: ploomber/ploomber ***@***.***>
Cc: Raffaele Olmeda ***@***.***>; Author ***@***.***>
Oggetto: Re: [ploomber/ploomber] Better support for PDF reports (Issue #672)


Thanks for your feedback! It makes sense to support different PDF converters, we'll add this to the roadmap. in the meantime, my recommendation is to output .ipynb in your pipeline.yaml and then convert them to PDF using nbconvert

**Comment by edublancas** [comment]
Great, does this solve the issue? If so, I'll close this and open a new one so we keep in mind to add support for other PDF converters.

**Comment by Ro-Ol** [comment]
Yes it does, just keeping in mind that in some cases the HTML format for inserting images could be the best choice

**Comment by edublancas** [comment]
agree! thanks for your feedback, keep an eye on https://github.com/ploomber/ploomber/issues/675 - we'll work on this soon :)
