### ISSUE TITLE
dag status validation

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#68]
When [assigning](https://github.com/ploomber/ploomber/blob/77d7dbf6b143ee17f886f76b6f3163d0ad5a39c9/src/ploomber/dag/dag.py#L252) the DAG status (e.g. up-to-date or outdated), we check that the tasks in the pipeline are set to valid values. For example, if we attempt to set the DAG status to `DAGStatus.Executed`, then all tasks must have either `TaskStatus.Executed` or `TaskStatus.Skipped` (you can see that validation [here](https://github.com/ploomber/ploomber/blob/77d7dbf6b143ee17f886f76b6f3163d0ad5a39c9/src/ploomber/dag/dag.py#L294)).

However, we're currently missing some tests here so there might be cases that are not correctly validated. Specifically, we're not testing scenarios where we set the DAG status to a few values and there are some `TaskStatus.Skipped` tasks.

**Comment by idomic** [comment]
@edublancas still relevant?
Please add more context on what needs to be done?

**Comment by edublancas** [comment]
yep, we're missing a few unit tests. update the description to add more detail. not critical though
