### ISSUE TITLE
Customizing logic using Python

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#681]
Currently, there is no way to customize `ploomber build` behavior, but in some cases, a user may want to override the default rules (i.e. execute a task when the code changes). This is possible by loading the `pipeline.yaml` into Python and then modifying the `DAG` object. This issue discusses some use cases as well as what we need to do to officially support this.

**Please comment if these examples solve your problem or if you have any other use cases we should also consider**

We've got a few example use cases:

## Skip a branch based on an input parameter

Say the pipeline looks like this:

```mermaid
graph LR;
    A-->B;
    A-->C;
    B-->D;
    C-->E;
```

In some cases, we may want to skip an entire branch (e.g. B -> D) based on an input parameter

[Working example](https://github.com/ploomber/projects/blob/ecdf9ad6af9fd2d8cc01d7b02077278ef3d16abb/cookbook/python-load/pipeline.py#L22)

```sh
# download example
ploomber examples -n cookbook/python-load --branch custom-logic -o python-load
cd python-load
```

### What's missing?

* While this is technically possible by deleting tasks one by one (e.g. `del dag['B']`), there isn't a simple way to delete an entire branch, so we should add a few handy methods (e.g., `dag.delete_branch('B')`)
* Add a cookbook example

## Customize caching logic

With long-running tasks, users may want to skip execution even if the code has slightly changed, or even apply custom rules, this usually happens with data ingestion tasks. It's possible to achieve that using private APIs

[Working example](https://github.com/ploomber/projects/blob/ecdf9ad6af9fd2d8cc01d7b02077278ef3d16abb/cookbook/python-load/pipeline.py#L40)

```sh
# download example
ploomber examples -n cookbook/python-load --branch custom-logic -o python-load
cd python-load
```

### What's missing

* We are lacking documentation on `TaskStatus` and currently the only way to achieve this is via the `dag._params.cache_rendered_status` private, we should make this a public API.
* Add a cookbook example

TO DO:

- [x] Add tutorial showing how to use Ploomber's CLI to call a factory entry point where the pipeline loads from a `pipeline.yaml` and `env.yaml` (show that cli args and cell injection work)
- [x] Add a link to the tutorial from the point above to the cookbook that shows how to load the dag using Python

**Comment by bmwilly** [comment]
Looks great, this solves my use case. 

Just one note: for something like `delete_branch`, you shouldn't just delete all downstream tasks of `B`. E.g., in

![Untitled Jam - 1](https://user-images.githubusercontent.com/3588399/160207553-eca8ec14-abf1-4fc0-9b52-df0cb80f87a3.png)

`F` is a downstream task of `B`, but should still be run after `E`.

**Comment by hornste** [comment]
caching logic looks good to me.

**Comment by edublancas** [comment]
awesome, @hornste: you can use the example for your purposes. It works well, we'll update it once we make it part of the public API.

hey @bmwilly, thanks for the feedback. There is one detail. If in the case you provided, we only delete B and D, then F won't run (since it'll expect a D task to be upstream, and it will throw an error since the DAG won't contain a D task). Any thoughts?

The only solution I can think of is using the [import_tasks_from](https://docs.ploomber.io/en/latest/api/spec.html?highlight=import_tasks_from#import-tasks-from) directive and building two pipelines. One where F has D and E as upstream, and a second one when it only has E.

**Comment by bmwilly** [comment]
@edublancas makes sense. The `import_tasks_from` directive plus what's outlined in this issue is perfect, and covers my use case.

**Comment by edublancas** [comment]
awesome, thanks for the feedback! I'll work on adding a bit more details to the examples I provided, merge them to the master branch, and open some issues to tackle the use of private APIs.

**Comment by mitch-at-orika** [comment]
looks good to me! Out of curiosity why is "--force" needed in the ignore_task example?
Also, Am I understanding these steps correctly with my explanation below:
    dag['create_file']._exec_status = TaskStatus.Skipped   #   give this task the status of "skipped" when running the pipeline
    dag._params.cache_rendered_status = True   #   make the pipeline believe that this task has been executed
If me above understanding is correct does that mean the tasks downstream of the skipped tasks can still run (i.e. it is up to user to ensure products are present). If so would'nt this be a better method than deleting the tasks in the other example? That would get around the issue raised by bmwilly?

**Comment by edublancas** [comment]
Thanks for your feedback! @mitch-at-orika 

Re `--force`: `--force` is needed to cover Steven's use case, he wants to skip a task even if passed the `--force` flag. In other cases, you may want to keep the `--force` functionality (which I think is what you want for your use case). So your code would look a bit different (I remember you mentioned on Slack you wanna customize the caching logic, so if you provide some details, I can help you with some guidelines).

Re deleting tasks: Ah, yes! That actually sounds better (marking as `Skipped` instead of deleting the tasks). This solves the problem that arises when deleting tasks. (hey @bmwilly - check this suggestion from @mitch-at-orika in the comment above)

**Comment by mitch-at-orika** [comment]
> Re `--force`: `--force` is needed to cover Steven's use case, he wants to skip a task even if passed the `--force` flag. In other cases, you may want to keep the `--force` functionality (which I think is what you want for your use case). So your code would look a bit different (I remember you mentioned on Slack you wanna customize the caching logic, so if you provide some details, I can help you with some guidelines).
> 
This is great content for a "--force" page in the docs. Would you contemplate a page that just explains --force? If it's not already in the docs somewhere that is..

Regarding my use case I have a pipeline that has a hierarchy of frequency of run. So outer to inner pipeline would be -> 
(indexed_by),( pipelines )
(__datatype_2D),(**Query**(network_model_links<->**bridgeing_format**<->**dataprocessing**(RAW_Queries)))
Then there is a task that brings back __datatype to a single data format to/from network_model etc.

I have been quite content with seperate pipelines manually called actually. However, it would be nice to have a json file out the front that tells a pipeline to run or not, all the way through, skipping as specified. But focusing on individual pipelines has been great for mapping the problem space. Another idea which I think may already be discussed parsing a standard markdown style graph file for the dag.. Then python can just update that as its going.. Ahh dreams... Anyway back to these pipelines!

**Comment by hornste** [comment]
hmmm. when I think of --force, I think it would run all the tasks, regardless of anything.

I wonder if there needs to be another setting, something like

--rebuild will rebuild everything except those marked to "skip"
--force build everything, regardless of it's marked to "skip"

don't know if rebuild is the right name or not.

**Comment by mitch-at-orika** [comment]
--rebuild is nice! then yeah you can do all the frequency logic in a outer python script by passing to "rebuild" a {task_num:skipped_bool} json, csv, pd.Series ,or dict?? Or I guess ploomber would just have a load_dag(dict) method?? or something?

**Comment by edublancas** [comment]
Yes, as the name suggests, `--force` should run everything regardless of anything. The case where we want to skip something "artificially" (that is, modifying Ploomber's standard behavior) is highly dependent on the use case. I think it's best to keep the current behavior (`--force` executes everything) and have users determine how they want to customize if needed - in 90% of the cases, the default behavior works.

For example, someone may decide to apply some very custom rules, and they can turn them on/off by adding an argument to the custom entry point:

```python
@with_env('env.yaml')
def make(env, custom_flag=False):
    # use custom_stuff to manually determine task status (override default behavior)
    dag = DAGSpec('pipeline.yaml', env=dict(env)).to_dag()
    return dag
```

Then the `custom_stuff` becomes accessible in the CLIL `ploomber build -e pipeline.make --custom-flag`

The benefit of using the Python API is that you can define your logic: as you mention @mitch-at-orika,  you can even write some logic that takes a JSON file and determines that task's status based on that.

Thanks for the feedback! I see a lot of value in explaining users how to customize the DAG execution logic so I'll add a tutorial showing all the things we've discussed here.

**Comment by edublancas** [comment]
Closing this. Moved the code examples to the master branch in the [projects repo](https://github.com/ploomber/projects/tree/master/cookbook/python-load) and created new issues for the pending changes.
