### ISSUE TITLE
Graphical DAG builder

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#687]
We've been getting feedback from users to have a UI to build the DAG. I'm thinking this could be embedded into Jupyter and then have changes in the UI to update the `pipeline.yaml`

Please add any thoughts/feedback!

**Comment by ScienceStanley** [comment]
Howdy guys!

I made a post on Twitter about a graphical DAG builder, and think this would be a amazing tool for Ploomber.

Can share some other tools that get much of the way there, but making workflows directly (visually) expressible/buildable would be so cool!

A lot of my work orbits around operationalizing workflow tools for scientists with minimal CD background, and for that use case a DAG builder would make Ploomber an awesome tool 🙏😇

**Comment by idomic** [comment]
@ScienceStanley would you like to add in here a few of those tools for reference?
You can also submit a PR if you're up for it! And we have the [community slack channel](https://ploomber.io/community) if there are challenges that comes up.

**Comment by ScienceStanley** [comment]
Yes!
The main one I have worked with in production is:

https://elyra.readthedocs.io/en/latest/getting_started/installation.html

Potentially could be a tool to integrate even 🤷‍♀️
I absolutely will take a running think at a PR 😇🙏
