### ISSUE TITLE
better error message when NotebookRunner is initialized with a string instead of a path

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#694]
`NotebookRunner` expects a string with Python code or a `pathlib.Path` object to a `.py` file. However, new users may do this:

```python
NotebookRunner('script.py')
```

But instead they should do:

```python
from pathlib import Path

NotebookRunner(Path('script.py'))
```

If passed a string, we should try to determine if the arguments "looks like a path to a file", and raise an error accordingly: "perhaps you meant passing a pathlib.path object".

**Comment by Zhenye-Na** [comment]
Created a CR for this issue, [link](https://github.com/ploomber/ploomber/pull/705)

Can you take a look at it when you got a chance? Thanks
