### ISSUE TITLE
Allow to customize task names when using grid

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#698]
This is related to #647 - we already allow custom product paths, but it is not possible to customize product paths

**Comment by jramirez857** [comment]
I am interested in taking this on!

**Comment by edublancas** [comment]
awesome! assigned. I think this one is straightforward. we just need to allow the user to use placeholders `[[something]]` to customize the task name.


So here we define the name:

https://github.com/ploomber/ploomber/blob/6f8a2547262d1bb7faadd268405a66c860be9b2a/src/ploomber/tasks/taskgroup.py#L185

But it should be something like this:

https://github.com/ploomber/ploomber/blob/6f8a2547262d1bb7faadd268405a66c860be9b2a/src/ploomber/tasks/taskgroup.py#L308

for context: https://github.com/ploomber/ploomber/issues/647

**Comment by jramirez857** [comment]
@edublancas Thank you for providing context! I have made progress here and wanted to get some clarification. Currently I have the test case below

```
def test_from_params_with_placeholder():
    dag = DAG()

    group = TaskGroup.from_params(PythonCallable,
                            File,
                            {'one': 'one.txt',
                            'another': 'another.txt'
                            }, {'source': touch},
                            dag,
                            name='example-task-[[param1]]--[[param2]]',
                            params_array=[{
                                'param1': '1',
                            }, {
                                'param2': 'a'
                            }])
    assert len(group) == 2
    assert dag['example-task-1--a']
```

This fails since the two task names in the output are `example-task-1-- and `example-task---a`. My questions are:
1. How should I be handling multiple parameters here? 
2. Is my assumption correct that the task should contain both parameters in the name?

Thanks for your help!

**Comment by edublancas** [comment]
For overall context: `TaskGroup` has two class methods: `from_params`, and `from_grid`, you can look at the source code for details but essentially the difference is that `from_params` receives an array of params, and then it passes each element to create a new task; this means (as you showed in your test case), that some tasks might not receive all params (the first one receives param1, and the second one param2). In contrast, `from_grid` receives a grid of parameters, then we compute the cross-product and initialize tasks, this guarantees that all tasks will receive the same param names.

> 1. How should I be handling multiple parameters here?

It's ok to have `example-task-1--` and `example-task---a`. if a parameter does not appear, it should just ignore it.

> 2\. Is my assumption correct that the task should contain both parameters in the name?

it's up to the user to decide which placeholders (e.g.,` [[placeholder]]`) to put in the name

Please add test cases for  `from_params`, and `from_grid`, I'd recommend you to start with `from_grid` since that's the most common use case

**Comment by jramirez857** [comment]
Hi @edublancas, I apologize for the day. Hopefully I should have the test case for `from_grid` available for PR with a couple days. If not, I will be at PyCon and would appreciate the assistance with this and https://github.com/ploomber/ploomber/pull/668#issuecomment-1100908509 during the sprints 😄

**Comment by edublancas** [comment]
hey @jramirez857 - no worries! You've been helping us a lot! Sure, I can give you a hand during PyCon - we'll actually be running a sprint, hope to see you there! And please stop by our booth!
