### ISSUE TITLE
PR CI failing

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#717]
I've noticed that PRs are failing because they are missing an API key to test the monitoring, but the normal CI is working so I think there is some misconfiguration, see this https://github.com/ploomber/ploomber/runs/6053740461?check_suite_focus=true

**Comment by idomic** [comment]
It seems the user doesn't run with a valid api key on the local. The ci has
the key configured under the git secrets.
This is an expected behaviour.
