### ISSUE TITLE
unused function?

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#718]
this function isn't called anywhere:

https://github.com/ploomber/ploomber/blob/343a831da26b20467e72da9d2f3ac57256dc1221/src/ploomber/telemetry/telemetry.py#L102

can we delete it?

**Comment by idomic** [comment]
I remember I wrote it so we can understand what's the version that's
running so we can solve faster end-user issues, wdyt?

**Comment by edublancas** [comment]
yeah. I see what the function is doing but it isn't called anywhere

**Comment by idomic** [comment]
Started a PR: https://github.com/ploomber/ploomber/pull/725
