### ISSUE TITLE
skipped tests

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#721]
I found that this test is skipped:

https://github.com/ploomber/ploomber/blob/962e2aa871fc1a6a2d71b10bac975a5cd692b6aa/tests/cli/test_custom.py#L210

I guess we can remove this since there's already logic that prevents the telemetry from being called in the CI?

**Comment by idomic** [comment]
@edublancas I don't see it in the master, maybe you removed it and forgot?
