### ISSUE TITLE
plotting with d3 backend

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#723]
- [ ] soorgeon: update pygraphviz message - it still prints a message saying pygraphviz is required
- [x] clear error message: many examples set the output path to `pipeline.png` - but this wont work if using the d3 backend
- [x] update documentation

**Comment by idomic** [comment]
happens after running Soorgeon refactor

**Comment by 94rain** [comment]
For the pygraphviz message in soorgeon, I guess I will just need to update this?

https://github.com/ploomber/soorgeon/blob/87c8f6d8a07d326528eb6b73c32007ab4e337595/src/soorgeon/cli.py#L70

```diff
-Plot pipeline (this requires pygraphviz, which isn't installed by default):
+Plot pipeline:
    $ ploomber plot
```

**Comment by idomic** [comment]
Yes exactly, and run the soorgeon refactor to make sure it doesn't print this anymore

**Comment by 94rain** [comment]
I will also remove the pygraphviz information from README. Will create a PR shortly.
