### ISSUE TITLE
reimplement multi-threaded downloads with async

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#724]
there are a few places where we are using multithreading to download files, but looks like using asyncio is a [better option](https://www.velotio.com/engineering-blog/async-features-in-python). we'd first have to do a quick implementation and see how much benefit it brings to consider migrating

**Comment by edilson258** [comment]
se for implementado do jeito certo, acredito que trará um ganho de performance, mesmo que não dê grande impacto fara diferença

**Comment by edublancas** [comment]
Yes, they are! I think we only have these two, although looking for ThreadPoolExecutor should give you all matches. Do you wanna work on this?

**Comment by neelasha23** [comment]
yes I can give it a try!

**Comment by edublancas** [comment]
awesome, please let us know if you see the performance improvements, we'd like to have some benchmarks before investing time in a full implementation

**Comment by neelasha23** [comment]
sure, I'll post here once I get some results on the performance

**Comment by neelasha23** [comment]
@edublancas 
For invoking the parallel download I was trying out this guide: https://github.com/ploomber/projects/tree/2e8d0436e13323939bba17ccda3a09fb0e75c7f6/guides/cloud-execution
However there seems to be some issue with the endpoint, have shared the stack trace with @idomic 

I'm also trying out this template: https://github.com/ploomber/projects/tree/master/templates/etl
But as far as I understood from the code here, the sqlite db should be on a remote server for the product metadata parallel download to work :
https://github.com/ploomber/ploomber/blob/d8880b5634dafb0d6bf01a161f133490955b2fce/src/ploomber/dag/util.py#L63

So which remote db should I specify in this example? 
Also, is this the right approach for doing the performance benchmark or you had something else in mind?

**Comment by edublancas** [comment]
Hi, thanks for the patience.

Using the cloud isn't ideal, since it hides a lot of the underlying process for [uploading](https://docs.ploomber.io/en/latest/api/_modules/clients/ploomber.clients.S3Client.html#ploomber.clients.S3Client.upload) products to S3 and we want a direct measurement. Ideally, we want to directly benchmark the uploading method in the S3 client (with the current implementation and with the async implementation) – apologies for including these details now, I didn't realize this before.

You can create a free AWS account for testing purposes, if you have a Google Cloud account, you may try with this other [client instead.](https://docs.ploomber.io/en/latest/api/_modules/clients/ploomber.clients.GCloudStorageClient.html#ploomber.clients.GCloudStorageClient)

But if none of these options work for you, feel free to pick another issue :)
