### ISSUE TITLE
Fix left bar scrolling CSS

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#727]
When expanding the left bar in the docs, the bottom sections are hidden - even if you scroll down, you won't see the **Community** section: 
![image](https://user-images.githubusercontent.com/989250/165167396-9b999fe1-37fa-43d8-8372-b80a8a6ca653.png)

**Comment by idomic** [comment]
@edublancas looks like this works in our current docs. Can we close?

**Comment by edublancas** [comment]
no, it doesn't work. we haven't fixed it

**Comment by edublancas** [comment]
fixed by #739
