### ISSUE TITLE
ensure algolia indexes the content of the snippets

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#752]
it looks like algolia is only indexing the text in our documentation. for example. if I'm interested in learning what the schema of the `meta` section is, I might look up "meta", but this doesn't take me to the schema docs. this was discovered by a user. here's more of his feedback:

```
Yes, I searched and read results for
DAGSpec
meta
```

and additionally reviewed

https://docs.ploomber.io/en/latest/user-guide/parametrized.html
https://docs.ploomber.io/en/latest/user-guide/configuration.html

**Comment by edublancas** [comment]
Note: whoever works on this might need access to the algolia console, ping me for access

**Comment by e1ha** [comment]
@edublancas Can you give me access?

**Comment by e1ha** [comment]
For the example about searching up meta and not getting schema docs I can see that when I search up meta it takes me only to the meta documentation https://docs.ploomber.io/en/latest/api/spec.html#meta . But you also want these https://docs.ploomber.io/en/latest/api/index.html (these are what you mean by schema docs?) to appear in the search results. Is this understanding correct?

**Comment by edublancas** [comment]
so we want the snippets to be searchable. a snippet is anything that looks like a terminal or text editor. for example, if I look up:

`path: path/to/sources`

this should show up: https://docs.ploomber.io/en/latest/api/spec.html#meta

since the `path: path/to/sources` appears in a snippet in that section

**Comment by e1ha** [comment]
Do we have a docsearch configuration file? Similar to the one referenced here https://docsearch.algolia.com/docs/legacy/config-file

**Comment by edublancas** [comment]
We don't have a config file. But ensure this still applies since when opening the link I see this is valid for the legacy version of doc search and we are using the latest one

**Comment by edublancas** [comment]
great! I tested it, and it works fine. Can you document the steps you followed? Add a section [here](https://github.com/ploomber/ploomber/blob/master/doc/CONTRIBUTING.md) and briefly describe how you managed to get this working.
