### ISSUE TITLE
Do not override user settings when running cloud set-key tests

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#758]
Some of the cloud tests call the set-key command to verify the functionality. However, this causes the user's existing key to be overridden after running the tests.

We should add a `pytest.fixture` that backs up the user settings and it restores them after the test runs. Essentially, we need to backup the file that stores the key.

https://github.com/ploomber/ploomber/blob/9e11fcbcdf763d6f3111e8254dc327a56306971e/tests/cli/test_cloud.py#L125

**Comment by dgdheeraj** [comment]
Hi @edublancas 
Can I try working on this?

**Comment by idomic** [comment]
@dgdheeraj feel free to submit a PR! Please make sure to go over our contribution guide and the OS blog https://ploomber.io/blog/open-source/
