### ISSUE TITLE
bash script for ploomber setup

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#759]
We've noticed that users struggle setting up ploomber, this mostly happens if they install it in an existing virtual environment that has many dependencies, if they have an outdated pip version, among other reasons.

an alternative would be to have a shell script (and possibly a script that works on windows as well) that installs ploomber in a clean environment, and do sanity checks (like run a sample pipeline), to ensure the user has a working environment. And if it isn't possible, suggest asking for help in https://ploomber.io/community

**Comment by edublancas** [comment]
having a docker image is also another possibility

**Comment by idomic** [comment]
I like the Docker option since we already have it as part of the hub.

**Comment by idomic** [comment]
We have a newer issue with more details in it #939 closing this one.
