### ISSUE TITLE
monitoring pipeline time out

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#760]
I started to see the timeout errors in the monitoring tests, thoughts?

https://github.com/ploomber/ploomber/runs/6428627745?check_suite_focus=true

https://github.com/ploomber/ploomber/runs/6428881522?check_suite_focus=true

https://github.com/ploomber/ploomber/runs/6428881754?check_suite_focus=true

I've re-added the `xfail` decorators because the CI breaks very often.

**Comment by idomic** [comment]
Fixed a few issues, please re-enable and let's see if it persists.

**Comment by edublancas** [comment]
I re-ran once, I didn't see the timeouts, but there's still one test failing: 

https://github.com/ploomber/ploomber/runs/6496335991?check_suite_focus=true
