### ISSUE TITLE
enable copy paste for inline examples

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#766]
We need to add some CSS and JS so the Python inline examples (the ones that start with `>>>` can be copied). This is how a non-Python example looks like:

![image](https://user-images.githubusercontent.com/989250/168489173-9f814d15-4ab7-45be-a4a7-d28753bbe6c8.png)

If the user clicks on the window, it'll copy the code. This is how a Python example looks like:

![image](https://user-images.githubusercontent.com/989250/168489187-7f5064e9-3e7c-4070-ad0e-aa0271cfe650.png)

We should add the window-like CSS and the copy functionality - the CSS and JS is already there, we just need to connect them with these other types of examples.

Source: https://docs.ploomber.io/en/latest/api/_modules/tasks/ploomber.tasks.PythonCallable.html#ploomber.tasks.PythonCallable

**Comment by e1ha** [comment]
commented

**Comment by edublancas** [comment]
FYI @e1ha check out https://github.com/ploomber/ploomber/pull/769

this contributor fixed the problem but the solution involved changing the existing snippets but we didn't merge it since we want to keep snippets unchanged

**Comment by edublancas** [comment]
Yes, we want to keep the snippets as is. e.g:

```python
>>> from ploomber.clients import SQLAlchemyClient
>>> client = SQLAlchemyClient('sqlite:///my_db.db')
>>> import sqlalchemy
>>> url = sqlalchemy.engine.url.URL.create(drivername='sqlite',
...                                        database='my_db.db')
>>> client = SQLAlchemyClient(url)
```

because adding `.. code-block:: python :class: python-console` will cause other issues.

> I'm a bit confused on how to run the docs for the Python API section in the website. I've been doing invoke docs like what it says in docs/contributing.md but whenever I edit the docstrings, the changes don't appear on the website. Is there a different way to run it? Thanks.

After running `invoke docs`, the docs should be available at `_build/html/index.html` Are you opening that local file? If so, and still cannot see the updated docs, please share the output of `invoke docs`

**Comment by e1ha** [comment]
I've created a PR with the output and my changes. Thank you!

**Comment by e1ha** [comment]
For automating the copy paste and window-like CSS and js does that only apply to the doctests?

**Comment by edublancas** [comment]
Yes, only doctests (any code block that starts with `>>>`)
