### ISSUE TITLE
Add full AWS and Google Cloud examples

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#771]
We currently don't have full examples for AWS and Google Cloud. This forces users to go around the docs to assemble their pipelines. Since consuming data from a warehouse, transforming and uploading results is a pretty typical use case, we should add some complete examples so users can get started quickly.

The main challenge is how to test them. For now, we can add them to the project's repository and test them manually, then at some point automate the testing process.

**Comment by edublancas** [comment]
google cloud example done: https://github.com/ploomber/projects/tree/master/templates/google-cloud

**Comment by edublancas** [comment]
I started digging into the AWS example, but Redshift isn't easy to setup

**Comment by idomic** [comment]
I think we should have an azure one too!
