### ISSUE TITLE
animation after opening docs

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#773]
When using the search feature, users might be directed to specific sections in the documentation. For example, if search for "schedule", the top [result is this](https://docs.ploomber.io/en/latest/deployment/batch.html#scheduling).

When clicking on it, the page scrolls down to the "Scheduling" section, however, it isn't clear to a user that such section is the one they should pay attention to. It'd better have some animation to draw attention to it, I've seen this on other websites.

**Comment by RodolfoFerro** [comment]
@Prathamesh010 I'll assign this issue to you in order to track any updates. I'll also review your PR (#1026) asap.

**Comment by Prathamesh010** [comment]
Yes, You can assign me this issue. :)
