### ISSUE TITLE
Remove pygraphviz from setup.py

### ISSUE THREAD

**Issue by reesehopkins** [ploomber/ploomber#784]
Love the d3 backend for the plotting the dag! 

`pygraphviz` is still listed as testing dependency in 
https://github.com/ploomber/ploomber/blob/master/setup.py

**Comment by edublancas** [comment]
yes! we decided to keep both backends since there are users who are used to the pygraphviz one. It shouldn't affect a regular installation since it isn't included by default. is this giving you trouble?

**Comment by reesehopkins** [comment]
Oh interesting. I wonder if it's another package that uses it. I'm building via poetry and pygraphviz gets installed as a dev dependency. I didn't want to include graphviz in my CI job.

**Comment by edublancas** [comment]
pygraphviz has never been a mandatory dependency, so sounds like the installation is coming from somewhere else - and I doubt poetry is installing ploomber's test dependencies. I'll close this now but feel free to re-open it if you need help
