### ISSUE TITLE
colab broken due to email prompt

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#786]
we recently added a prompt for new users to submit their email; however, this doesn't work in jupyter notebooks (including colab):

```sh
# this breaks
! ploomber examples -n {example} -o {out}
```

see https://github.com/ploomber/projects/issues/37 for reference

solving it for colab is simple since it sets and env variable, we can check for it and skip the email prompt if it appears. for jupyter, we can do something similar but I don't know if jupyter sets an environment variable

*Note: I removed the README link to colab*

**Comment by 94rain** [comment]
I think the email prompt actually works in Colab. The other issue is not about the email prompt but about plotting.

I am able to enter my email here:

<img width="623" alt="image" src="https://user-images.githubusercontent.com/21193371/168940112-6a5e5817-f961-46ee-8998-527a701f826d.png">

After entering my email and pressing return:

<img width="646" alt="image" src="https://user-images.githubusercontent.com/21193371/168940196-f6e60b66-54d2-4cca-92c0-200062b5ef97.png">

**Comment by edublancas** [comment]
oh, thanks for letting me know.

So I dug a bit more. As you mention, the email prompt works, but it's very confusing since the field isn't visible (I had to scroll down a bit until I found it) – so I think we should fix this as well.

The error you reported is coming from IPython, colab runs a very old version (5.5.0), when I tried to upload it, I saw this:

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jupyter-console 5.2.0 requires prompt-toolkit<2.0.0,>=1.0.0, but you have prompt-toolkit 3.0.29 which is incompatible.
**google-colab 1.0.0 requires ipython~=5.5.0, but you have ipython 7.33.0 which is incompatible.**
google-colab 1.0.0 requires tornado~=5.1.0; python_version >= "3.0", but you have tornado 6.1 which is incompatible.
Successfully installed ipython-7.33.0 prompt-toolkit-3.0.29
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Upgrading IPython makes the error go away, but it seems like we're stuck. If we keep the old IPython, colab complains, but if we upgrade it, colab may break.

**Comment by 94rain** [comment]
Should we enforce package versions in `setup.py` or just add a few (un)install commands at the top of the notebook? The packages in colab env is quite inconsistent with my local env.

If we just want to do the latter, I think we can just uninstall the google-colab library since it is not being used. 

* We can simply remove all packages first by using`!pip uninstall -y -r <(pip freeze)` and then reinstall the required packages, but this would increase the bootstrap time to 2 minutes. 

* Otherwise, we need to run at least the following: (jupyter_client is for resolving incompatibility during`ploomber build`). However, for upgrading `jupyter_client` I need to restart the runtime afterward, which is very inconvenient.
    ```shell
    !pip -q uninstall google-colab -y
    !pip -q install ipython tornado jupyter-console jupyter_client --upgrade
    ```

**Comment by edublancas** [comment]
thanks for digging into this. so just to ensure we're on the same page: the email prompt has been removed so it's no longer an issue. so we're left with the following (correct me if I'm wrong):

1. error message when downloading the example (pasted error below, I think this is what you are referring to)
2. the environment is very inconsistent

error:

```pytb
Loading examples...
[TerminalIPythonApp] WARNING | GUI event loop or pylab initialization failed

UnknownBackendTraceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py in enable_matplotlib(self, gui)
   2953         # Now we must activate the gui pylab wants to use, and fix %run to take
   2954         # plot updates into account
-> 2955         self.enable_gui(gui)
   2956         self.magics_manager.registry['ExecutionMagics'].default_runner = \
   2957             pt.mpl_runner(self.safe_execfile)

/usr/local/lib/python3.7/dist-packages/IPython/terminal/interactiveshell.py in enable_gui(self, gui)
    512         if gui:
    513             self.active_eventloop, self._inputhook =\
--> 514                 get_inputhook_name_and_func(gui)
    515         else:
    516             self.active_eventloop = self._inputhook = None

/usr/local/lib/python3.7/dist-packages/IPython/terminal/pt_inputhooks/__init__.py in get_inputhook_name_and_func(gui)
     36 
     37     if gui not in backends:
---> 38         raise UnknownBackend(gui)
     39 
     40     if gui in aliases:

UnknownBackend: No event loop integration for 'inline'. Supported event loops are: qt, qt4, qt5, gtk, gtk2, gtk3, tk, wx, pyglet, glut, osx
```


I ran a quick test and it looks like if we upgrade ipython at the beginning the error goes away and the example works correctly. is there anything else left? if the colab env is inconsistent, perhaps generating a requirements.txt with pinned versions will help. we'd us this only for colab, and leave the setup.py as is.

thoughts?

**Comment by 94rain** [comment]
> it looks like if we upgrade ipython at the beginning the error goes away and the example works correctly

Indeed things are working smoothly despite the incompatibility messages and there will be nothing left. If we try to resolve the incompatibility, more errors will show up... We can just ignore the messages for simply running the example.

> perhaps generating a requirements.txt with pinned versions will help

I don't know how this works for colab. Looks like colab only reads the *.ipynb. Or do we want to keep a long list of `!pip install  package<version` at the bootstrap part?

**Comment by edublancas** [comment]
> I don't know how this works for colab. Looks like colab only reads the *.ipynb. Or do we want to keep a long list of `!pip install package <= version` at the bootstrap part?

I was thinking something like 

```
pip install -r https://github.com/ploomber/ploomber/blob/master/dev/requirements-colab.lock.txt
```

let's try `requirements-colab.lock.txt` approach. if that works, that will be a more robust solution.

**Comment by 94rain** [comment]
Just to confirm, do we put `requirements-colab.lock.txt` in `ploomber` repo, or `projects` repo instead?

**Comment by edublancas** [comment]
ploomber repo
