### ISSUE TITLE
make >>> unselectable in the documentation

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#791]
Our docstring examples need to start with `>>>` for pytest to detect them as tests. [Example](https://docs.ploomber.io/en/latest/api/_modules/tasks/ploomber.tasks.PythonCallable.html#ploomber.tasks.PythonCallable):

```python
>>> from pathlib import Path
>>> from ploomber import DAG
>>> from ploomber.tasks import PythonCallable
>>> from ploomber.products import File
>>> from ploomber.executors import Serial
>>> dag = DAG(executor=Serial(build_in_subprocess=False))
>>> def my_function(product):
...     # create data.csv
...     Path(product).touch()
>>> PythonCallable(my_function, File('data.csv'), dag=dag)
PythonCallable: my_function -> File('data.csv')
>>> summary = dag.build()
```

However, if users want to select them, they'll also copy the `>>>` characters, and it will break if they put it in the Python interpreter (although IPython is smart enough to ignore them).

I noticed that the [pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html#pandas.DataFrame.groupby) documentation prevents the user from selecting them, along with the `...` characters:

![image](https://user-images.githubusercontent.com/989250/169142593-4946ad50-f76c-470b-9a35-b7970b6177d3.png)

we should to the same

**Comment by Dark-Knight11** [comment]
Hi, I would like to work on this issue. Can you please me direct to the file where changes are to be made?
(I guess it is the CSS file for the docs site but I'm unable to find the file in the repo)

**Comment by edublancas** [comment]
sure: https://github.com/ploomber/ploomber/blob/master/doc/_static/css/custom-theme.css

instructions to build the docs: https://github.com/ploomber/ploomber/blob/master/doc/CONTRIBUTING.md
