### ISSUE TITLE
outdated install guide needs to be removed

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#798]
This can be found along the docs and it should point to the quick-start guide. We need to update those. https://docs.ploomber.io/en/latest/get-started/install.html

**Comment by edublancas** [comment]
so this link is broken, are you saying we have this link in the `doc/` directory?

**Comment by idomic** [comment]
It's happening in the projects repo, there are instances of this old guide where instead it should be the quickstart:
i.e.: 
cookbook/dynamic-params/README.md:2
guides/cron/README.md:2
 and more, there are like 30+ instances of it

**Comment by edublancas** [comment]
got it! so for reference, here's the broken link (install Ploomber): 

![image](https://user-images.githubusercontent.com/989250/169561587-f8f5bd6d-953b-457f-bdee-ba436b6fc577.png)

we need to replace: https://docs.ploomber.io/en/latest/get-started/install.html
with https://docs.ploomber.io/en/latest/get-started/quick-start.html

here: https://github.com/ploomber/projects

**Comment by edublancas** [comment]
fixed https://github.com/ploomber/projects/issues/38
