### ISSUE TITLE
copying code in console snippets ignores line break

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#803]
when clicking on console snippets:

![image](https://user-images.githubusercontent.com/989250/169677547-18fde026-2e17-4659-ad78-16639b3027da.png)

https://docs.ploomber.io/en/docs/use-cases/research.html

The contents are copied to the clipboard, but the line break is ignored, causing the clipboard to contain:

```
pip install ploomberploomber examples -n cookbook/grid -o grid
```

when it should be:

```
pip install ploomber
ploomber examples -n cookbook/grid -o grid
```

**Comment by Sync271** [comment]
Hey, do I make a PR to the docs branch or master? Asking because the changes that are live aren't from master, but from "docs" branch and [doc/CONTRIBUTING.md](https://github.com/ploomber/ploomber/blob/master/doc/CONTRIBUTING.md) doesn't specify anything about it.

**Comment by edublancas** [comment]
please submit the PR to the master branch, thanks!

**Comment by Sync271** [comment]
The code block you are referring to isn't on master yet.

master branch:
https://github.com/ploomber/ploomber/blob/596d503515b9b25c499cfd18184304fbc5810174/doc/use-cases/research.rst#L29-L40

docs branch:
https://github.com/ploomber/ploomber/blob/8854aeddffeb6a276563efc44a991089bc6cafd3/doc/use-cases/research.rst#L29-L44

 What do you suggest I do?

**Comment by edublancas** [comment]
I think there should be similar snippets in the master branch.

But feel free to open a PR to the docs branch. I'll merge it soon anyway.

Just ensure that the changes apply to all similarly looking snippets:

```
.. code-block: console

    some-code
```

**Comment by Sync271** [comment]
@edublancas 
Sorry, I didn't understand the problem clearly earlier and maybe spoke too early before looking into the problem😅!
I've made a PR with the fix now.
