### ISSUE TITLE
add did you mean feature to `ploomber examples`

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#805]
We should add the "did you mean?" feature when executing `ploomber examples`

```sh
 ploomber examples -n cookbook/fileclient -o fileclient
```

```txt
There is no example named "cookbook/fileclient", did you mean "cookbook/file-client"?
```

for reference: We already have this built-in in other places https://github.com/ploomber/ploomber/blob/907c5ed798354efbedc5f4cfd397179e75812ec5/src/ploomber_cli/cli.py#L17

**Comment by aadityasinha-dotcom** [comment]
Can you explain this issue?
