### ISSUE TITLE
Search doesn't find gpu

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#809]
When using the algolia search for GPUs, it finds main pages that has the headline of GUide and not one of the cloud gpu parameters for instance.

**Comment by idomic** [comment]
It doesn't work with metadata? maybe we can add tags on the snippets

**Comment by edublancas** [comment]
It's not the metadata, it's the snippet's content. For example, here:

![image](https://user-images.githubusercontent.com/989250/169938611-485da10b-ce56-4a31-b9e2-1eaf2f1a9f6e.png)

The algolia crawler will index the text (e.g., "for each task...") but it wont index the content of the YAML snippet.

**Comment by idomic** [comment]
This is what I meant with metadata: https://www.algolia.com/doc/framework-integration/symfony/indexing/configure-searchable-data/

We can define a custom crawler that gets the snippet, parse the yaml and perform search on all of it.
