### ISSUE TITLE
CI failures - R

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#818]
Sometimes the CI is failing on R issues like:
  Error: Failed to get R 4.2.0: Failed to get R 4.2.0: Failed to download version 4.2.0: Error: getaddrinfo ENOTFOUND cdn.rstudio.com
We should add a retry mechanism or perhaps fix this initial error:
https://github.com/ploomber/ploomber/runs/6625950342?check_suite_focus=true

**Comment by idomic** [comment]
Fixed, changed the CI setup R version to 2.2.2.

**Comment by edublancas** [comment]
does changing the R version fixes the issue? I'm guessing it's an intermittent problem and it'll come back again. the issue is probably the latency of the server hosting R's source code

**Comment by idomic** [comment]
It did, I'll run a few more times to see if it persists.

**Comment by idomic** [comment]
This still persists even with the new issue, reopened

**Comment by edublancas** [comment]
there's nothing we can do here. unless we stop using the action and use another source. but I think let's close this

**Comment by idomic** [comment]
Yeah, I changed something in the CI and it solved it. closing.
