### ISSUE TITLE
clean traceback when using `ploomber task`

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#828]
when `ploomber build` fails, we format the traceback so it's easier for a user to see what's going on. here's where we call it:

https://github.com/ploomber/ploomber/blob/06c8c7ccd165e220745aaba71881b3bdc5aa4621/src/ploomber/executors/serial.py#L217

and here's the code to format the exception:

https://github.com/ploomber/ploomber/blob/master/src/ploomber/executors/_format.py

However, this code only runs when executing a pipeline (it's not executed when running a single task), this implies that:

```
ploomber task {task-name}
``` 

will have a verbose and hard-to-read output. We should use the same code to clean up so it's easier to read. this is particularly important since ploomber cloud runs `ploomber task` under the hood (instead of `ploomber build`)

**Comment by idomic** [comment]
Nice job @grnnja
