### ISSUE TITLE
use IFrame to display embedded D3 plot

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#842]
when generating a pipeline plot with the D3 backend with `output='embed'`:

https://github.com/ploomber/ploomber/blob/77d7dbf6b143ee17f886f76b6f3163d0ad5a39c9/src/ploomber/dag/dag.py#L893

we use the requests-html library to load the HTML file since we need to execute the embedded JS for the plot to display:

https://github.com/ploomber/ploomber/blob/77d7dbf6b143ee17f886f76b6f3163d0ad5a39c9/src/ploomber/dag/plot.py#L66

and then we render the plot with a `IPython.display.HTML` object, this allows us to embed the plot in Jupyter. However, as pointed in https://github.com/ploomber/projects/issues/42 IPython has an `IFrame` object that correctly displays HTML and runs JS.

We should remove the requests-html code and substitute it for using `IFrame`

**Comment by imskr** [comment]
Can I work on this?

**Comment by edublancas** [comment]
sure!

**Comment by imskr** [comment]
Hi @edublancas I'm having trouble adding IFrame in place of requests-html. Can you give me some pointer? Thanks

**Comment by idomic** [comment]
@imskr can you be more specific? What issues are you having?

Basically you need to import:

`import from IPython.display import IFrame`

and then replace:

` _embedded_html(path=path)`

with

`IFrame(src=path)`

**Comment by imskr** [comment]
Understood Thanks @idomic
