### ISSUE TITLE
`test_plot_with_d3_embed` intermittent test

### ISSUE THREAD

**Issue by 94rain** [ploomber/ploomber#862]
We noticed one intermittent test here:

https://github.com/ploomber/ploomber/runs/6924703945?check_suite_focus=true

`ERROR tests/dag/test_dag.py::test_plot_with_d3_embed[d3] - PermissionError: [...`

`PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpgp5lfqh9'`

**Comment by edublancas** [comment]
yeah, I've seen it before. I tried to debug it but it doesn't fail on my windows machine.

**Comment by edublancas** [comment]
@idomic - it'd be great if we can assign this issue for this week's sprint

**Comment by edublancas** [comment]
can you point me to the line where we are using `shutil.rmtree`? I'll take a look and see if it's safe to ignore errors

**Comment by 94rain** [comment]
Here in tmp_directory(): https://github.com/ploomber/ploomber/blob/6986b5f3f27b57ce9072e78a0472a89aa37206dc/tests/conftest.py#L145

**Comment by edublancas** [comment]
ok, we can remove that. that's only used as part of the test suite cleanup. please add a little note explaining why we added the `ignore_errors` flag
