### ISSUE TITLE
doc: code snippets embedded in documentation pdf output is hard to read

### ISSUE THREAD

**Issue by 94rain** [ploomber/ploomber#865]
I downloaded a pdf version of ploomber documentation from https://docs.ploomber.io/_/downloads/en/stable/pdf/.

There are many code snippets that are not easy to read because of the light font color or lack of black background.

For example, in Page 19:
<img width="815" alt="image" src="https://user-images.githubusercontent.com/21193371/174334847-51ad85d5-e7de-49dc-8a78-bd91ca97cf78.png">

**Comment by edublancas** [comment]
thanks for reporting this. I think people rarely use the pdf format, so maybe we should just remove it? thoughts?

**Comment by idomic** [comment]
@edublancas initially we've added it to support a user request. Some users might generate reports through this right?

**Comment by edublancas** [comment]
what kind of reports?

**Comment by idomic** [comment]
Maybe for EDA to share internally?
#672 #658

**Comment by edublancas** [comment]
weird. it looks like it's turned off, no idea why PDF still shows up 
<img width="660" alt="image" src="https://user-images.githubusercontent.com/989250/174394778-da3a09fd-f1d7-46d3-9117-df079aa4c516.png">
