### ISSUE TITLE
integration tests are failing

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#881]
https://github.com/ploomber/ploomber/runs/7042482430?check_suite_focus=true

The quick solution to that is having a new run, getting the run and task id pushed to replace the hardcodes, what we should do here is make sure we can run the test without errors, to solve this we can run the cloud pipeline and get the task/run id dynamically. We should also explore where this logs we're expecting are going to and how we can retain those.

**Comment by Wxl19980214** [comment]
Do I have access to aws batch? Like the thing you showed me last time when we try to debug the error?

**Comment by idomic** [comment]
Yeah it's in the AWS account, you should have access to debug.

**Comment by Wxl19980214** [comment]
@edublancas 
Do you think we can dynamically get run_id and task_id by running ploomber cloud build in our tests and then get the running task info? Ido says this might increase the CI time.

**Comment by idomic** [comment]
Yes the tradeoff here is 20+ minutes to our CI.
Either we do that, or we run the cloud one nightly, and list the latest runs/tasks and consume it without creating it.

**Comment by idomic** [comment]
Making this an env_var should be the first step (obviously will make it easier). Not sure about coupling the CIs though, sounds like something we should avoid.

**Comment by edublancas** [comment]
so I looked at the failing test. the one that's failing is the one that retrieves logs. I think let's keep it simple for now since I'd like the CI to be passing so we can make a new release.

this is the failing test:

```
     def test_cloud_logs(runid):
        runner = CliRunner()
        result = runner.invoke(cli, ['cloud', 'logs', runid])
>       assert 'START OF LOGS FOR TASK' in result.output
E       AssertionError: assert 'START OF LOGS FOR TASK' in ''
E        +  where '' = <Result okay>.output
```

I think let's change the assert condition to check the exit code, I think click exposes something like:

```
assert result.ok
```

we just want to check that the command runs without issues. then, we can think of how to we implement a long-term solution to get a valid  run_id

**Comment by Wxl19980214** [comment]
Ok for now I will submit a PR to just check this command exit gracefully.

**Comment by edublancas** [comment]
right, exit_code is what we want

**Comment by Wxl19980214** [comment]
Ok we have that at the end. I will just remove all other assertion for now
