### ISSUE TITLE
`test_cloud.py` has a lot of xskip and xfail tests

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#891]
`test_cloud.py` has a lot of `xskip` and `xfail` tests. I checked the  git history and realized I added those flags since the tests were timing out. I also had to add the flags to two new tests since the backend is broken. These tests are unreliable and fail very often. I'm unsure what the solution is here but we've been trying out fixes without success (we merge to master and errors appear again). Also, I think these should be moved to the integration tests suite.

**Comment by idomic** [comment]
@Wxl19980214 we had some issue with the cloud, can you retry now?
I ran this locally and it all pass (make sure you reference the CI key like this `PLOOMBER_CLOUD_KEY=SOME_KEY`).
If that passes for you we can remove the `@pytest.mark.xfail(reason="timing out")` and skips.
We should also move this module into the integration tests.
