### ISSUE TITLE
Autocomplete editor for `pipeline.yaml`

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#893]
Most of our users interact with Ploomber via a `pipeline.yaml`; which has a pre-defined [schema.](https://docs.ploomber.io/en/latest/api/spec.html#spec-api-pipeline-yaml) However, this isn't friendly for beginners who don't know the allowed values. The idea is to build a Jupyter plug-in that adds autocomplete. Note that this is a big feature, so let's go step by step and figure out things along the way.

We want to build this as a JupyterLab extension. Here's the documentation to [build extensions](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#), here's a [tutorial](https://jupyterlab.readthedocs.io/en/stable/extension/extension_tutorial.html) that shows how to build a simple extension, and here's a list of [examples.](https://github.com/jupyterlab/extension-examples)

Based on [this](https://github.com/jupyterlab/extension-examples#about-jupyterlab), it looks like JupyterLab provides re-usable components:

> Some of the higher level components that can be used are **text editors,** terminals, notebooks, interactive widgets, filebrowser, renderers for different file formats that provide access to an enormous ecosystem of libraries from different languages.

so the first thing to figure out is how to re-use the existing text editor and add the autocomplete feature. Essentially, we want something like [this](https://github.com/jupyterlab/extension-examples/tree/master/completer) but inside the text editor (not the notebook interface).

Note that a similar feature is already built-in (you we might want to look at JupyerLab's source code to get some inspiration):

![image](https://user-images.githubusercontent.com/989250/177451909-d7db04a4-c439-4e18-9e31-12ec87989d8e.png)

To see it in action:

1. Create a file with .py extension on JupyterLab
2. Open the file
3. Right click on the editor window and click "Create Console for Editor"
4. Then add some Python code (e.g. "import") and hit tab

We essentially want the same thing except for files named `pipeline.yaml` and without the requirement to click on "create a console for editor".

Some tasks to get started:

- [ ] figure out how to add a custom text editor that re-uses the one that JupyterLab provides
- [ ] add an autocomplete feature (show the tooltip when pressing the tab key) with some dummy values

**Comment by edublancas** [comment]
assigned!

**Comment by e1ha** [comment]
I wanted to clarify a few things: 
1. For the test editor, would the functionality consist of the user clicking a button on the menu panel or searching for the text editor on a command palette and then a text editor would pop up and the user can type on the test editor? 

2. Can you expand on what you mean by "re-use the existing text editor"? Jupyterlab has a codeeditor module and other modules related to editors and so far, I've been looking into using those. (ie see https://jupyterlab.readthedocs.io/en/stable/api/modules/codeeditor.html) Is that the right track?

**Comment by edublancas** [comment]
yes, jupyterlab has an existing code editor component so we should use this. the link you shared looks like it is what we want

**Comment by e1ha** [comment]
How do you want to navigate this feature? Right now I have Command L to trigger it and the up and down arrows to navigate the tooltip, enter to submit, arrow right to clear or clicking outside the div to clear the tooltip without submitting. Does that sound alright?

**Comment by idomic** [comment]
Maybe having a way to play with it might be easier to see the UX?
like if we deploy it on some jupyterlab instance. I think the shortcut is great, we should definitely have some button to launch this.

**Comment by edublancas** [comment]
I think we should mimic the standard behavior of the existing autocompletion. In jupyter, it's triggered with the tab key. 

I agree with Ido, please push your changes so we can play around with it
