### ISSUE TITLE
`_suggest_command` does not work for some examples

### ISSUE THREAD

**Issue by 94rain** [ploomber/ploomber#895]
See https://github.com/ploomber/ploomber/pull/825#issuecomment-1171692773

`_suggest_command` returns `None` for the input `grid` but we expect `cookbook/grid`. There may be some other cases that do not work as well.

**Comment by edublancas** [comment]
yeah, i tried a few. I think we can fix it if we adjust the parameters to the `get_close_matches`, let's get the PR merged and then we can work on this as a follow-up
