### ISSUE TITLE
Fixing font size in dag plot when using D3 (CSS/HTML/JS)

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#903]
When tasks have long titles, the text goes over the limits of the task. We should adjust the text size automatically to fit the node:

![image (1)](https://user-images.githubusercontent.com/989250/177886227-132ab401-9021-4c3e-b045-fe4bb7fc1b8b.png)

**Comment by e1ha** [comment]
Can you link me to an example of these dag plots on the website?

**Comment by idomic** [comment]
@e1ha You'd have to generate it (I sent you in slack a sample html).
You can use any of the templates, use: `ploomber plot --backend d3` (make sure you're on the latest version).
You'd also need to make sure the task name is long enough to overflow.

**Comment by e1ha** [comment]
Is there any way for me to test if it'll work? I have a solution and I've tested that it would work on my generated html documents by appending the code to the document but I don't know of a way that I would be able to test it just by calling `ploomber plot --backend d3`.

**Comment by edublancas** [comment]
yeah:

```sh
ploomber examples -n templates/ml-basic -o ml
cd ml
```

then modify the `pipeline.yaml` and add really long names. example:

```yaml
  - source: tasks.get
    product: '{{folder}}/get.parquet'
    name: this-is-a-really-long-name
```

**Comment by e1ha** [comment]
Yeah I've been manually adding my code to the generated pipeline.html after calling `ploomber plot --backend d3` and it works. I've added the solution code to `ploomber/src/ploomber/resources/dag_template.html` and I was wondering if I could test that the code would appear in every pipeline.html. Or should I just push it first?

**Comment by edublancas** [comment]
yeah your modifications should appear whenever you run `ploomber plot`. if you don't, it's likely that you don't have ploomber installed in editable mode:

```
pip uninstall ploomber
# move to the cloned repo
pip install -e .
```

then verify:


```python
import ploomber
ploomber
```

this should print the location, and it should be the local copy
