### ISSUE TITLE
checkpointing notebooks

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#918]
In https://github.com/ploomber/ploomber/issues/917, we discussed dumping the interpreter's state for later debugging. This issue discusses how we can further improve the experience.

Picture this: a user runs a notebook, and it crashes. They start a debugging session and fix (?) the code. They call `ploomber build` again, but the notebook still fails, so they have to repeat the process. Debugging takes some iterations to get right, especially when debugging code that transforms data frames; errors might come from some faulty rows that break certain transformations. Checkpointing can help users accelerate the debugging process.

For example, if my notebook looks like this:

```python
# cell 1
df = long_operation()

# cell 2
df2 = transformation(df)

# cell 3 - notebook breaks here!
df3 = another_transformation(df)
```

I have to re-run my notebook from the beginning to see if my code changes fix the issue. But we could checkpoint it, so it resumes execution from, say, cell 3. It isn't yet clear how this should work since fixing a bug in cell 3 might need changes elsewhere. But this is the idea.

**Comment by amardeep** [comment]
[Hex](https://hex.tech/) notebook (not opensource) does something interesting here. They maintain a graph view of the cells, and can run only affected subset of the graph when a cell changes.

https://learn.hex.tech/docs/develop-logic/compute-model/reactive-execution

**Comment by edublancas** [comment]
reactive kernels are great! there are a few open source projects I've seen but none of then have taken off - perhaps we'll work on it at some point
