### ISSUE TITLE
adding warning on Python 3.6 deprecation

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#926]
We won't be supporting Python 3.6 beginning in Ploomber 0.20

There's a PR that removes everything related to it: https://github.com/ploomber/ploomber/pull/876

But we haven't sent any warnings to users

we should add one here: https://github.com/ploomber/ploomber/blob/master/src/ploomber/__init__.py

essentially, if we detect they're running 3.6, we should display a message

that should be released in the next 0.19 release. on 0.20, we merge https://github.com/ploomber/ploomber/pull/876 and remove the warning

**Comment by 94rain** [comment]
The master branch of Ploomber can no longer be installed on 3.6 (either `invoke deploy` or `pip install` will fail) due to the `nbclient>=0.6.1` requirement.

**Comment by edublancas** [comment]
thanks for the heads up @94rain! So now it seems we cannot ship the papermill debugging feature in the next 0.19.x release since that will break python 3.6

**Comment by idomic** [comment]
So what's the path forward? Sounds like it's already broken + blocking a major feature.

**Comment by edublancas** [comment]
I think let's add a warning if running on python 3.6 and say that some stuff might not work well and tell users that they  should either downgrade ploomber or upgrade python

**Comment by idomic** [comment]
Sounds good! Do we wait on the debugging feature?
@94rain Please open a PR as described above for the user warning.

**Comment by 94rain** [comment]
I tried to remove the `nbclient>=0.6.1` requirement, and install nbclient 0.5.9 instead (which still supports 3.6). 

Then I ran `python -c "import ploomber"` (with python 3.6). The `__init__.py` will fail at the import part before the warning. Do we want to add the warning before the import part?

```bash
(ploomber) ➜ /workspaces/ploomber (3.6_deprecation_warning ✗) $ python -c "import ploomber"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/workspaces/ploomber/src/ploomber/__init__.py", line 4, in <module>
    from ploomber.dag.dag import DAG
  File "/workspaces/ploomber/src/ploomber/dag/dag.py", line 84, in <module>
    from ploomber import executors
  File "/workspaces/ploomber/src/ploomber/executors/__init__.py", line 1, in <module>
    from ploomber.executors.serial import Serial
  File "/workspaces/ploomber/src/ploomber/executors/serial.py", line 7, in <module>
    from ploomber.executors import _format
  File "/workspaces/ploomber/src/ploomber/executors/_format.py", line 5, in <module>
    from papermill.exceptions import PapermillExecutionError
  File "/home/codespace/.conda/envs/ploomber/lib/python3.6/site-packages/papermill/__init__.py", line 4, in <module>
    from .execute import execute_notebook
  File "/home/codespace/.conda/envs/ploomber/lib/python3.6/site-packages/papermill/execute.py", line 10, in <module>
    from .engines import papermill_engines
  File "/home/codespace/.conda/envs/ploomber/lib/python3.6/site-packages/papermill/engines.py", line 425, in <module>
    papermill_engines.register_entry_points()
  File "/home/codespace/.conda/envs/ploomber/lib/python3.6/site-packages/papermill/engines.py", line 38, in register_entry_points
    self.register(entrypoint.name, entrypoint.load())
  File "/home/codespace/.conda/envs/ploomber/lib/python3.6/site-packages/entrypoints.py", line 79, in load
    mod = import_module(self.module_name)
  File "/home/codespace/.conda/envs/ploomber/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/workspaces/ploomber/src/ploomber/papermill/__init__.py", line 10, in <module>
    from ploomber.papermill.client import PloomberNotebookClient
  File "/workspaces/ploomber/src/ploomber/papermill/client.py", line 10, in <module>
    from nbclient.util import ensure_async, run_hook, run_sync
ImportError: cannot import name 'run_hook'
```

**Comment by edublancas** [comment]
i think it should work if the warnings comes before the ` from ploomber.dag.dag import DAG` line, which is what's causing the exception

**Comment by 94rain** [comment]
```python
import warnings
from sys import version_info
if version_info < (3, 7):
    warnings.warn('Ploomber 0.20 will no longer be supported in Python 3.6.\n'
                  'Please either downgrade ploomber or '
                  'upgrade your Python version to 3.7+.')
```
```bash
(ploomber) ➜ /workspaces/ploomber (3.6_deprecation_warning ✗) $ python -c "import ploomber"
/workspaces/ploomber/src/ploomber/__init__.py:5: UserWarning: Ploomber 0.20 will no longer be supported in Python 3.6.
Please either downgrade ploomber or upgrade your Python version to 3.7+.
  warnings.warn('Ploomber 0.20 will no longer be supported in Python 3.6.\n'
```
OK, it's simple. 

Do we want to do this for CLI as well? `src/ploomber/__init__.py` only works for `import ploomber`. Is  `src/ploomber_cli/__init__.py` the right place? I tried to insert the same snippet there but it does not work for CLI. I took a look at `src/ploomber_cli/cli.py` but there seems not to be a way to have the warning before all messages.

**Comment by idomic** [comment]
> Do we want to do this for CLI as well? src/ploomber/__init__.py only works for import ploomber. Is src/ploomber_cli/__init__.py the right place? I tried to insert the same snippet there but it does not work for CLI. I took a look at src/ploomber_cli/cli.py but there seems not to be a way to have the warning before all messages.

Does this fail as well? In my opinion it won't get to the CLI code since it'll throw the warning and error before it right?

**Comment by 94rain** [comment]
> > Do we want to do this for CLI as well? src/ploomber/**init**.py only works for import ploomber. Is src/ploomber_cli/**init**.py the right place? I tried to insert the same snippet there but it does not work for CLI. I took a look at src/ploomber_cli/cli.py but there seems not to be a way to have the warning before all messages.
> 
> Does this fail as well? In my opinion it won't get to the CLI code since it'll throw the warning and error before it right?

I just double-checked with some commands:
With deprecation warnings only in `ploomber/__init__.py`:
* `ploomber` command: will not output any warning (Is this expected?)
* `ploomber build` command: output the warning from `src/ploomber/__init__.py`

With deprecation warnings in both `ploomber/__init__.py` and `ploomber_cli/__init__.py`:
* `ploomber`: output only the warning from `ploomber_cli/__init__.py`
* `ploomber build`: output two warnings from both `src/ploomber/__init__.py` and `ploomber_cli/__init__.py` (will output two warnings, CLI warning goes first)
```
(ploomber) ➜ /workspaces/ploomber/ml (3.6_deprecation_warning ✗) $ ploomber build
/workspaces/ploomber/src/ploomber_cli/__init__.py:5: UserWarning: Ploomber 0.20 will no longer support Python 3.6.
Please upgrade your Python version to 3.7+.
  warnings.warn("Ploomber 0.20 will no longer support Python 3.6.\n"
Loading pipeline...
/workspaces/ploomber/src/ploomber/__init__.py:5: UserWarning: Ploomber 0.20 will no longer be supported in Python 3.6.
Please either downgrade ploomber or upgrade your Python version to 3.7+.
```

**Comment by idomic** [comment]
Let's cover both just to stay on the safe side.
I don't see users just running `ploomber` without any arguments.

**Comment by edublancas** [comment]
note: we should also include the command to downgrade in case the users want that:

`pip install ploomber==0.19`

**Comment by 94rain** [comment]
Updated in the PR
```bash
(ploomber) /workspaces/ploomber (3.6_deprecation_warning ✗) $ ploomber
/workspaces/ploomber/src/ploomber_cli/__init__.py:4: UserWarning: Ploomber 0.20 will no longer be supported in Python 3.6.
Please either downgrade ploomber by running `pip install ploomber==0.19` or upgrade your Python version to 3.7+.
  warnings.warn('Ploomber 0.20 will no longer be supported in Python 3.6.\n'
```
