### ISSUE TITLE
Typo in the "tasks[*].grid" paragraph

### ISSUE THREAD

**Issue by CoralieXXC** [ploomber/ploomber#933]
Documentation page: api/spec:
I think there is a typo in the "tasks[*].grid" paragraph (if I understand well - correct me if I misunderstood):
"The spec above generates nine tasks for each combination of parameters with products random-forest-X.html where X goes from 0 to 8. Task names also include a suffix."
should probably be:
"The spec above generates **six** tasks for each combination of parameters with products random-forest-X.html where X goes from 1 to 6. Task names also include a suffix." (as also written in the code in [https://docs.ploomber.io/en/latest/cookbook/grid.html](https://docs.ploomber.io/en/latest/cookbook/grid.html): # creates 6 tasks (3 * 2)).

**Comment by edublancas** [comment]
you're right! I fixed the error, the updated docs will be up in a few mins. thanks for your feedback!

**Comment by CoralieXXC** [comment]
You're welcome. Thanks for this awesome and most useful project!

**Comment by idomic** [comment]
Feel free to join our [community channel](https://ploomber.io/community)
We'd love to have your feedback!
