### ISSUE TITLE
Sample webapp that converts ipynb into PDF reports

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#934]
This is a placeholder issue.
We'd like to have a public webapp that will allow users drop notebooks into the GUI, convert it into a PDF report after running it.
Then the user will have the output of the notebook run on the right screen and on the left side of the screen there'll be an option to get the pdf report.

**Comment by edublancas** [comment]
I think we want to skip running notebooks for now since that complicates things a lot.

MVP can be: drop a notebook, get the notebook in PDF

we can do this with nbconvert

**Comment by idomic** [comment]
@edublancas so a notebook with empty output on the cells? I think we can easily run it via a lambda

**Comment by edublancas** [comment]
no, the idea is that the user already ran the notebook file, so it contains the outputs

**Comment by edublancas** [comment]
this creates prettier PDFs: https://quarto.org/

**Comment by edublancas** [comment]
might be useful https://github.com/jupyter/nbviewer

**Comment by edublancas** [comment]
this is done convert.ploomber.io
