### ISSUE TITLE
improving the onboarding tutorial - your first pipeline

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#936]
We want to improve the onboarding experience of the basic tutorials on binder.

## general observations

* the objective of the initial tutorial should be to convince people to give ploomber a try. the current version tries to teach them ploomber, we want to change that. our value proposition should be clear: ploomber allows you to run more experiments faster
* since our purpose is to convince, there is no need to show low-level details like the pipeline.yaml. We can mention it and add a link to open it, but it should be optional
* there is no context on the dataset. the example analyzes covid data; we should make a few comments on it during the example; telling a story will make it more compelling
* we should simplify and prettify the output HTML reports. hide code, make the plots prettier (use ggplot [style](https://matplotlib.org/stable/gallery/style_sheets/ggplot.html)), larger fonts, etc. 
* I think (?) the sample dataset has data per country, we could select a single country (or maybe continent if there's a continent column), then, at the end of the tutorial, show that they can go and change the initial task, re-run the pipeline and re-generate all outputs for the new country. we can implement this with a pipeline parameter so the outputs are stored in different folders, and the user can switch the parameter to generate the outputs for the new country
* the pipeline should generate both ipynb and HTML outputs. at the end of the tutorial, [we can use this](https://sklearn-evaluation.readthedocs.io/en/latest/user_guide/NotebookCollection.html) to explore the outputs from the ipynb files
* instead of using shell commands (e.g. `ploomber build`), we should using the Python API because this one has a better experience when executed on a notebook. e.g. shell commands get stuck while running, while the Python API shows a progress bar
* I enabled on binder the option to open py files as notebooks with a single click, we should update the tutorial since it says that you need to do right click

## libraries

I came across two projects that can help us improve the onboarding experience on binder.

[ipylab](https://github.com/jtpio/ipylab) allows interacting with the frontend from Python. This can effectively demonstrate what Ploomber is doing as the user progresses in a specific tutorial. For example, in the introduction tutorial (that users might run from Binder), we could open the data preview after we run the pipeline, the HTML reports, etc. 

[jupyterlab-tour](https://github.com/jupyterlab-contrib/jupyterlab-tour) allows creating a "tour" on JupyterLab by highlighting specific areas in the user interface. I'm unsure how granular it is since it looks like it only allows to highlight of entire UI sections, so not sure how useful this could be.

##

share your feedback while searching the docs

**Comment by idomic** [comment]
@edublancas I think we can close this as most of those issues went to the ploomber-intro.
Feel free to reopen
