### ISSUE TITLE
script for easy installation

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#939]
Many users get stuck while trying to install ploomber. When checking it out for the first time, many go to the terminal and run `pip install ploomber`.  However, if they have an existing environment with lots of packages, they're running on windows, among other factors. Chances are, the pip command will fail.

A script that takes care of this can significantly simplify the process for users. We can do this with a Python script, this will make it easier to embed logic, and it's more portable (we want this to work well on windows). Initially, we can aim to get it working on Python 3.7 and over. Note that given the nature of this task, the script should only use the standard library and not any external packages.

## basic logic

* check Python version >= 3.7
* if conda is available, use it to create the virtual environment
* if conda is not available, use [venv](https://docs.python.org/3/library/venv.html) 
* install ploomber
* print follow-up steps (include command on for activating the virtual env)

Much of this logic is already here, so we can use it as reference: https://github.com/ploomber/ploomber/blob/master/src/ploomber/cli/install.py

## some other ideas

* if docker is available, this can simplify things a lot, but maybe for v2
* to know if this is successful, we should implement some anonymous telemetry (not sure what's the easiest option here). perhaps we can create a netlify app, hit a URL with different parameters and then look at the analytics. we want to record: python version, if docker is available, and if the script was successful or not
* we could go beyond installing ploomber and start jupyterlab, check that the jupyterlab extension works, and maybe even starting jupyterlab with an interactive tutorial (see this https://github.com/ploomber/ploomber/issues/936)

**Comment by idomic** [comment]
How is that different than : https://github.com/ploomber/ploomber/blob/master/src/ploomber/cli/install.py ?
I think this install automation can easily become a Dockerfile to install a container.

**Comment by edublancas** [comment]
> How is that different than : https://github.com/ploomber/ploomber/blob/master/src/ploomber/cli/install.py ?

this requires ploomber to be installed already. getting there is the point of this issue

> I think this install automation can easily become a Dockerfile to install a container.

we should not assume the user has docker installed

**Comment by e1ha** [comment]
For using conda to create a virtual environment, I should not assume that the user has an environment.yml file right?

**Comment by idomic** [comment]
Yes we shouldn't assume any pre requisite is met. This should cover
everything from running the script to a working env, ploomber and jupyter
lab
