### ISSUE TITLE
readme improvements

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#940]
Our README has too many options and people get lost. It should be clear how to get started.

I think it should only give two options: running the onboarding tutorial locally or taking them to the first tutorial.

and we should replace this with a larger button since people don't see it:

![image](https://user-images.githubusercontent.com/989250/180618941-50d24ed6-8d66-4352-bc67-41ae8137358a.png)

**Comment by grnnja** [comment]
by "taking them to the first tutorial" do you mean the docs or the binder

**Comment by idomic** [comment]
I think running it locally, or running the tutorial via binder. And the binder option should have a larger attention-grabbing button.
