### ISSUE TITLE
do not require a parameters cell in the Python API

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#950]
Currently, we throw an error if the notebooks are missing a parameters cell, but this is too restrictive; we should show a warning instead.

I think this does don't happen with the spec API and we add the parameters cell, but I must check.

**Comment by 94rain** [comment]
Hi @edublancas. Have you already started to work on this? I see it is also assigned to me on Asana.

Are these tests related?
https://github.com/ploomber/ploomber/blob/d0c25f41d0fc74778eb1a3b21a486fbf1028893c/tests/sources/test_notebooksource.py#L259-L275

**Comment by idomic** [comment]
@edublancas please provide some context? 
@94rain I don't think this issue started since I don't see any commits.

**Comment by edublancas** [comment]
you can work on this @94rain 

yeah the tests you mentioned are related. in the past, we enforced having a parameters cell (that's why you see we're throwing an error if it's not there), but now we decided to relax that. however, I think we should throw a warning - hence the test should verify that the warning is displayed.

the critical detail here is the pipeline.yaml API already implements this (it doesn't require a parameters cell, adding one if missing), see here:

https://github.com/ploomber/ploomber/blob/05147759c615011bbaf0922ea0ca1caa5beee68d/src/ploomber/spec/dagspec.py#L810

so essentially, we want to move the logic from there to NotebookRunner so it works both when users use a pipeline.yaml and the Python API directly.

**Comment by 94rain** [comment]
I guess we need to do this for ScriptRunner as well?

I am thinking of creating a method `_validate_parameters_cell(source, is_notebook=True)` in `src/ploomber/tasks/notebook.py` similar to `_post_init_validation` (outside of class definition), passing if it is a script or notebook by an argument and letting it be called by both NotebookRunner and ScriptRunner.

https://github.com/ploomber/ploomber/blob/d0c25f41d0fc74778eb1a3b21a486fbf1028893c/src/ploomber/sources/notebooksource.py#L409-L441

**Comment by edublancas** [comment]
you can implement this in NotebookMixin, this way NotebookRunner and ScriptRunner will inherit it

**Comment by 94rain** [comment]
`dagspec` contains `extract_up` and `extract_prod` when calling `add_parameters_cell(path, extract_upstream, extract_product)`. Do we want to keep these two arguments? If so, we may need to pass these as arguments to `NotebookRunner._init_source`. Or can we always write `upstream = None\n product = None` to the parameters cell?
```
    extract_up = dag_spec['meta']['extract_upstream']
    extract_prod = dag_spec['meta']['extract_product']
```
https://github.com/ploomber/ploomber/blob/0c7f7ac5a2a03b93402caabc00f473a54e9f15c3/src/ploomber/sources/notebooksource.py#L1039-L1055

(If we keep these two arguments) How about the case when we directly call NotebookRunner? Do we want to set default value of `extract_upstream`, `extract_product` to True?

**Comment by edublancas** [comment]
Good point; both `extract_up` and `extract_prod` are only applicable when called from dagspec, so we have to keep that logic. However, when users use the Python API directly, these parameters are not applicable, and we should call the `add_parameters_cell` function with both `False`

**Comment by 94rain** [comment]
#971 is now ready for review.
