### ISSUE TITLE
document early stop

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#953]
raising this:

https://github.com/ploomber/ploomber/blob/2fe474987ae6fca088e02399dbff99672a17fc95/src/ploomber/exceptions.py#L83

will exit the DAG gracefully, but it's undocumented

**Comment by shizuchanw** [comment]
I just finished reading CONTRIBUTING.md; which page do you think would be a good place to put this documentation?

**Comment by idomic** [comment]
A simple search [here](docs.ploomber.io) would've given you the answer:
https://docs.ploomber.io/en/latest/api/_modules/executors/ploomber.executors.Serial.html#ploomber-executors-serial

Also please connect with Prem, he recently pushed a doc fix so he might be able to help and review it.

**Comment by shizuchanw** [comment]
> A simple search [here](https://docs.ploomber.io) would've given you the answer: https://docs.ploomber.io/en/latest/api/_modules/executors/ploomber.executors.Serial.html#ploomber-executors-serial
> 
> Also please connect with Prem, he recently pushed a doc fix so he might be able to help and review it.

Thank you for the reference! And I'll connect with Prem.

**Comment by shizuchanw** [comment]
> please also document it here: https://docs.ploomber.io/en/latest/api/_modules/executors/ploomber.executors.Parallel.html#ploomber.executors.Parallel
> 
> I think the best way to do this is by adding examples of how this works. you can use the tests we have as a reference:
> 
> https://github.com/ploomber/ploomber/blob/4643e0f69e058c5ed0c26f16b0486386958a6d47/tests/dag/test_dag.py#L974
> 
> https://github.com/ploomber/ploomber/blob/4643e0f69e058c5ed0c26f16b0486386958a6d47/tests/dag/test_dag.py#L981
> 
> in the examples, just call `dag.build`, instead of doing `assert dag.build() is None`
> 
> also, it's important to mention that this only works for function tasks (PythonCallable), if the user has a notebook task, then they need to go with a task-level hook (which is what we show in the second example I shared)

Thank you so much!! I just wrote a few examples and created a PR on this.
