### ISSUE TITLE
docs are missing some examples

### ISSUE THREAD

**Issue by idomic** [ploomber/ploomber#965]
Documentation page: get-started/basic-concepts

We can give the readers more context by adding our examples into the relevant section, for instance:

The [cell injection process](https://docs.ploomber.io/en/latest/get-started/basic-concepts.html#the-cell-injection-process) can have the example on [pipeline parameterization](https://github.com/ploomber/projects/blob/master/guides/parametrized/pipeline.yaml)

**Comment by Mustapha-AJEGHRIR** [comment]
Should we add other examples ? or the the `pipeline parameterization` ?

**Comment by idomic** [comment]
Let's start with this one first.

**Comment by Mustapha-AJEGHRIR** [comment]
I have opened a PR #1029
