### ISSUE TITLE
CI improvements

### ISSUE THREAD

**Issue by edublancas** [ploomber/ploomber#984]
Our CI is getting slow and clunky; here are a few things we can do:

* The integration tests have steps that we don't need. example: `r-lib/actions/setup-r@v2`, installing graphviz, running doctests
* I started to see some intermittent failures, we should investigate
* And the last thing (which will take more time to solve): Sometimes dependencies update, and it's hard to debug

For example, a few tests suddenly started failing. After spending >2 hours investigating the issue, I found that this papermill PR was the cause: https://github.com/nteract/papermill/pull/673 - I fixed it in the master branch, but then, we had an open PR who had forked the master branch *before* I fixed the papermill issue. So what happened is that PR was also failing, and it took me like 15 minutes to remember that it was because of the papermill issue.

I'm unsure what the best solution is. But I'm thinking of something like this: we can keep track of the version of our dependencies our CI is using; if the CI fails, it should first check if the libraries we use had recent updates. If so, add a little warning saying:

> papermill has been updated recently. here's the changelog: URL

possibly something we can add [here](https://github.com/ploomber/pkgmt)

**Comment by idomic** [comment]
Why don't we just fix it on the Ploomber engine and consume it?

**Comment by edublancas** [comment]
ploomber engine still uses papermill as dependency (for now)

**Comment by idomic** [comment]
Yeah, I guessed, so maybe the quick fix is changing it.
