### ISSUE TITLE
Not generating upstream nor products dictionaries

### ISSUE THREAD

**Issue by molgor** [ploomber/ploomber#987]
Hi,
I'm using ploomber version 0.20. I  followed the video tutorials and online documentation and cannot make ploomber to add the 'upstream = {data:  ....,}' and 'products' dictionaries as a cell in the task.py file. I had reloaded the file from disk, reloaded the kernel, etc. It seems that this feature is not in my current version.  How can I diagnose this behavior? 
Apart from this ploomber seems to work great.

Many thanks,

Juan

**Comment by molgor** [comment]
Hi Eduardo, 
Thank you for the resource. I could make it work with Jupyter lab. 
The problem was that I'm using the Jupyter version of Django (i.e. Jupyter via Django shell_plus). I thought that it was using the same Jupyter instance but it seems that there is a problem with this particular configuration (perhaps the extension is not installed). I'll try to diagnose and document it here. Thank you for your help.

**Comment by edublancas** [comment]
Sure,

I'm closing this now but feel free to re-open it if you need more help.

As an alternative, you can manually inject the cells to the notebooks with:

```
ploomber nb --inject
```

**Comment by idomic** [comment]
@molgor feel free to [join our community](https://ploomber.io/community/) for more support or feature requests!
